#!/bin/bash

## Download the standalone debs for headless-host
## Make a personal apt miror from these files

sudo apt download acpi
sudo apt download acpid
sudo apt download adduser
sudo apt download adwaita-icon-theme
sudo apt download aglfn
sudo apt download alsa-oss
sudo apt download alsa-utils
sudo apt download alsamixergui
sudo apt download amd64-microcode
sudo apt download anacron
sudo apt download ant
sudo apt download ant-contrib
sudo apt download ant-optional
sudo apt download anthy
sudo apt download anthy-common
sudo apt download apparmor
sudo apt download apt
sudo apt download apt-listchanges
sudo apt download apt-utils
sudo apt download arandr
sudo apt download arc-theme
sudo apt download aspell
sudo apt download aspell-am
sudo apt download aspell-ar
sudo apt download aspell-ar-large
sudo apt download aspell-bg
sudo apt download aspell-bn
sudo apt download aspell-ca
sudo apt download aspell-cs
sudo apt download aspell-cy
sudo apt download aspell-da
sudo apt download aspell-de
sudo apt download aspell-el
sudo apt download aspell-eo
sudo apt download aspell-es
sudo apt download aspell-et
sudo apt download aspell-eu
sudo apt download aspell-eu-es
sudo apt download aspell-fa
sudo apt download aspell-fr
sudo apt download aspell-ga
sudo apt download aspell-gl-minimos
sudo apt download aspell-gu
sudo apt download aspell-he
sudo apt download aspell-hi
sudo apt download aspell-hr
sudo apt download aspell-hu
sudo apt download aspell-is
sudo apt download aspell-it
sudo apt download aspell-kk
sudo apt download aspell-ku
sudo apt download aspell-lt
sudo apt download aspell-lv
sudo apt download aspell-ml
sudo apt download aspell-mr
sudo apt download aspell-nl
sudo apt download aspell-no
sudo apt download aspell-pa
sudo apt download aspell-pl
sudo apt download aspell-pt-br
sudo apt download aspell-pt-pt
sudo apt download aspell-ro
sudo apt download aspell-ru
sudo apt download aspell-sk
sudo apt download aspell-sl
sudo apt download aspell-sv
sudo apt download aspell-ta
sudo apt download aspell-te
sudo apt download aspell-tl
sudo apt download aspell-uk
sudo apt download asymptote
sudo apt download asymptote-doc
sudo apt download at-spi2-core
sudo apt download autoconf
sudo apt download automake
sudo apt download autopoint
sudo apt download autotools-dev
sudo apt download avahi-autoipd
sudo apt download base-files
sudo apt download base-passwd
sudo apt download bash
sudo apt download bash-completion
sudo apt download bc
sudo apt download biber
sudo apt download bidiv
sudo apt download bind9-host
sudo apt download binfmt-support
sudo apt download binutils
sudo apt download binutils-common
sudo apt download binutils-x86-64-linux-gnu
sudo apt download blt
sudo apt download bluetooth
sudo apt download bluez
sudo apt download bridge-utils
sudo apt download broadcom-sta-dkms
sudo apt download bsdmainutils
sudo apt download bsdutils
sudo apt download bubblewrap
sudo apt download build-essential
sudo apt download busybox
sudo apt download bzip2
sudo apt download ca-certificates
sudo apt download ca-certificates-java
sudo apt download ca-certificates-mono
sudo apt download chktex
sudo apt download cli-common
sudo apt download cm-super
sudo apt download cm-super-minimal
sudo apt download coinor-libcbc3
sudo apt download coinor-libcgl1
sudo apt download coinor-libclp1
sudo apt download coinor-libcoinmp1v5
sudo apt download coinor-libcoinutils3v5
sudo apt download coinor-libosi1v5
sudo apt download conky
sudo apt download conky-std
sudo apt download console-setup
sudo apt download console-setup-linux
sudo apt download context
sudo apt download context-modules
sudo apt download coreutils
sudo apt download cpio
sudo apt download cpp
sudo apt download cpp-8
sudo apt download crda
sudo apt download cron
sudo apt download culmus
sudo apt download curl
sudo apt download dash
sudo apt download dbus
sudo apt download dbus-user-session
sudo apt download dbus-x11
sudo apt download dconf-cli
sudo apt download dconf-gsettings-backend
sudo apt download dconf-service
sudo apt download debconf
sudo apt download debconf-i18n
sudo apt download debhelper
sudo apt download debian-archive-keyring
sudo apt download debian-faq
sudo apt download debian-reference-common
sudo apt download debian-reference-es
sudo apt download debian-reference-it
sudo apt download debianutils
sudo apt download default-jre
sudo apt download default-jre-headless
sudo apt download desktop-file-utils
sudo apt download devhelp
sudo apt download devhelp-common
sudo apt download dh-autoreconf
sudo apt download dh-python
sudo apt download dh-strip-nondeterminism
sudo apt download dhcpcd-dbus
sudo apt download dhcpcd5
sudo apt download dia
sudo apt download dia-common
sudo apt download dia-shapes
sudo apt download dialog
sudo apt download dictionaries-common
sudo apt download diffutils
sudo apt download dirmngr
sudo apt download distro-info-data
sudo apt download dkms
sudo apt download dmidecode
sudo apt download dmsetup
sudo apt download dns-root-data
sudo apt download dnscrypt-proxy
sudo apt download dnsmasq
sudo apt download dnsmasq-base
sudo apt download doc-debian
sudo apt download dos2unix
sudo apt download dosfstools
sudo apt download dpkg
sudo apt download dpkg-dev
sudo apt download dvidvi
sudo apt download dvipng
sudo apt download dwm
sudo apt download dwz
sudo apt download e2fsprogs
sudo apt download eject
sudo apt download elinks
sudo apt download elinks-data
sudo apt download emacs
sudo apt download emacs-bin-common
sudo apt download emacs-common
sudo apt download emacs-el
sudo apt download emacs-gtk
sudo apt download emacsen-common
sudo apt download enchant
sudo apt download ethtool
sudo apt download exfat-fuse
sudo apt download exfat-utils
sudo apt download exim4-base
sudo apt download exim4-config
sudo apt download exim4-daemon-light
sudo apt download exo-utils
sudo apt download exuberant-ctags
sudo apt download fakeroot
sudo apt download fbterm
sudo apt download fdisk
sudo apt download feh
sudo apt download feynmf
sudo apt download ffmpegthumbnailer
sudo apt download file
sudo apt download findutils
sudo apt download firebird3.0-common
sudo apt download firebird3.0-common-doc
sudo apt download firebird3.0-server-core
sudo apt download firebird3.0-utils
sudo apt download firefox-esr
sudo apt download firmware-amd-graphics
sudo apt download firmware-brcm80211
sudo apt download firmware-iwlwifi
sudo apt download firmware-linux-free
sudo apt download firmware-linux-nonfree
sudo apt download firmware-misc-nonfree
sudo apt download fontconfig
sudo apt download fontconfig-config
sudo apt download fonts-adf-accanthis
sudo apt download fonts-adf-berenis
sudo apt download fonts-adf-gillius
sudo apt download fonts-adf-universalis
sudo apt download fonts-arabeyes
sudo apt download fonts-arphic-bkai00mp
sudo apt download fonts-arphic-bsmi00lp
sudo apt download fonts-arphic-gbsn00lp
sudo apt download fonts-arphic-gkai00mp
sudo apt download fonts-baekmuk
sudo apt download fonts-cabin
sudo apt download fonts-comfortaa
sudo apt download fonts-croscore
sudo apt download fonts-crosextra-caladea
sudo apt download fonts-crosextra-carlito
sudo apt download fonts-dejavu
sudo apt download fonts-dejavu-core
sudo apt download fonts-dejavu-extra
sudo apt download fonts-droid-fallback
sudo apt download fonts-ebgaramond
sudo apt download fonts-ebgaramond-extra
sudo apt download fonts-font-awesome
sudo apt download fonts-freefont-otf
sudo apt download fonts-freefont-ttf
sudo apt download fonts-gfs-artemisia
sudo apt download fonts-gfs-baskerville
sudo apt download fonts-gfs-bodoni-classic
sudo apt download fonts-gfs-complutum
sudo apt download fonts-gfs-didot
sudo apt download fonts-gfs-didot-classic
sudo apt download fonts-gfs-gazis
sudo apt download fonts-gfs-neohellenic
sudo apt download fonts-gfs-olga
sudo apt download fonts-gfs-porson
sudo apt download fonts-gfs-solomos
sudo apt download fonts-gfs-theokritos
sudo apt download fonts-go
sudo apt download fonts-hosny-amiri
sudo apt download fonts-inconsolata
sudo apt download fonts-ipaexfont-gothic
sudo apt download fonts-ipaexfont-mincho
sudo apt download fonts-ipafont-gothic
sudo apt download fonts-ipafont-mincho
sudo apt download fonts-junicode
sudo apt download fonts-lato
sudo apt download fonts-liberation
sudo apt download fonts-liberation2
sudo apt download fonts-linuxlibertine
sudo apt download fonts-lmodern
sudo apt download fonts-lobster
sudo apt download fonts-lobstertwo
sudo apt download fonts-noto-core
sudo apt download fonts-noto-hinted
sudo apt download fonts-noto-mono
sudo apt download fonts-noto-ui-core
sudo apt download fonts-oflb-asana-math
sudo apt download fonts-open-sans
sudo apt download fonts-opensymbol
sudo apt download fonts-roboto-unhinted
sudo apt download fonts-sil-gentium
sudo apt download fonts-sil-gentium-basic
sudo apt download fonts-sil-gentiumplus
sudo apt download fonts-sil-gentiumplus-compact
sudo apt download fonts-sil-padauk
sudo apt download fonts-stix
sudo apt download fonts-texgyre
sudo apt download fonts-tlwg-garuda
sudo apt download fonts-tlwg-garuda-otf
sudo apt download fonts-tlwg-kinnari
sudo apt download fonts-tlwg-kinnari-otf
sudo apt download fonts-tlwg-laksaman
sudo apt download fonts-tlwg-laksaman-otf
sudo apt download fonts-tlwg-loma
sudo apt download fonts-tlwg-loma-otf
sudo apt download fonts-tlwg-mono
sudo apt download fonts-tlwg-mono-otf
sudo apt download fonts-tlwg-norasi
sudo apt download fonts-tlwg-norasi-otf
sudo apt download fonts-tlwg-purisa
sudo apt download fonts-tlwg-purisa-otf
sudo apt download fonts-tlwg-sawasdee
sudo apt download fonts-tlwg-sawasdee-otf
sudo apt download fonts-tlwg-typewriter
sudo apt download fonts-tlwg-typewriter-otf
sudo apt download fonts-tlwg-typist
sudo apt download fonts-tlwg-typist-otf
sudo apt download fonts-tlwg-typo
sudo apt download fonts-tlwg-typo-otf
sudo apt download fonts-tlwg-umpush
sudo apt download fonts-tlwg-umpush-otf
sudo apt download fonts-tlwg-waree
sudo apt download fonts-tlwg-waree-otf
sudo apt download fonts-ubuntu
sudo apt download fonts-ubuntu-console
sudo apt download fonts-unfonts-core
sudo apt download fonts-unfonts-extra
sudo apt download fortune-mod
sudo apt download fortunes-debian-hints
sudo apt download fortunes-it
sudo apt download fragmaster
sudo apt download freeglut3
sudo apt download fuse
sudo apt download g++
sudo apt download g++-8
sudo apt download gcc
sudo apt download gcc-8
sudo apt download gcc-8-base
sudo apt download gcr
sudo apt download gdb
sudo apt download gdbm-l10n
sudo apt download gdisk
sudo apt download geany
sudo apt download geany-common
sudo apt download geany-plugin-addons
sudo apt download geany-plugin-autoclose
sudo apt download geany-plugin-automark
sudo apt download geany-plugin-codenav
sudo apt download geany-plugin-commander
sudo apt download geany-plugin-ctags
sudo apt download geany-plugin-defineformat
sudo apt download geany-plugin-doc
sudo apt download geany-plugin-extrasel
sudo apt download geany-plugin-gendoc
sudo apt download geany-plugin-geniuspaste
sudo apt download geany-plugin-git-changebar
sudo apt download geany-plugin-insertnum
sudo apt download geany-plugin-keyrecord
sudo apt download geany-plugin-latex
sudo apt download geany-plugin-lineoperations
sudo apt download geany-plugin-lipsum
sudo apt download geany-plugin-lua
sudo apt download geany-plugin-macro
sudo apt download geany-plugin-miniscript
sudo apt download geany-plugin-numberedbookmarks
sudo apt download geany-plugin-overview
sudo apt download geany-plugin-pairtaghighlighter
sudo apt download geany-plugin-pg
sudo apt download geany-plugin-pohelper
sudo apt download geany-plugin-prettyprinter
sudo apt download geany-plugin-prj
sudo apt download geany-plugin-projectorganizer
sudo apt download geany-plugin-sendmail
sudo apt download geany-plugin-shiftcolumn
sudo apt download geany-plugin-spellcheck
sudo apt download geany-plugin-tableconvert
sudo apt download geany-plugin-treebrowser
sudo apt download geany-plugin-updatechecker
sudo apt download geany-plugin-vc
sudo apt download geany-plugin-workbench
sudo apt download geany-plugin-xmlsnippets
sudo apt download geany-plugins
sudo apt download geany-plugins-common
sudo apt download geoip-database
sudo apt download gettext
sudo apt download gettext-base
sudo apt download ghostscript
sudo apt download giblib1
sudo apt download gimp
sudo apt download gimp-data
sudo apt download gir1.2-atk-1.0
sudo apt download gir1.2-atspi-2.0
sudo apt download gir1.2-dbusmenu-glib-0.4
sudo apt download gir1.2-dbusmenu-gtk3-0.4
sudo apt download gir1.2-freedesktop
sudo apt download gir1.2-gck-1
sudo apt download gir1.2-gcr-3
sudo apt download gir1.2-gdkpixbuf-2.0
sudo apt download gir1.2-glib-2.0
sudo apt download gir1.2-gtk-2.0
sudo apt download gir1.2-gtk-3.0
sudo apt download gir1.2-harfbuzz-0.0
sudo apt download gir1.2-ibus-1.0
sudo apt download gir1.2-notify-0.7
sudo apt download gir1.2-pango-1.0
sudo apt download git
sudo apt download git-man
sudo apt download glade
sudo apt download glib-networking
sudo apt download glib-networking-common
sudo apt download glib-networking-services
sudo apt download gnome-accessibility-themes
sudo apt download gnome-icon-theme
sudo apt download gnome-keyring
sudo apt download gnome-keyring-pkcs11
sudo apt download gnome-power-manager
sudo apt download gnome-settings-daemon-common
sudo apt download gnome-themes-extra
sudo apt download gnome-themes-extra-data
sudo apt download gnupg
sudo apt download gnupg-l10n
sudo apt download gnupg-utils
sudo apt download gnuplot-data
sudo apt download gnuplot-x11
sudo apt download gobject-introspection
sudo apt download golang
sudo apt download golang-1.11
sudo apt download golang-1.11-doc
sudo apt download golang-1.11-go
sudo apt download golang-1.11-src
sudo apt download golang-doc
sudo apt download golang-go
sudo apt download golang-src
sudo apt download gparted
sudo apt download gpg
sudo apt download gpg-agent
sudo apt download gpg-wks-client
sudo apt download gpg-wks-server
sudo apt download gpgconf
sudo apt download gpgsm
sudo apt download gpgv
sudo apt download grep
sudo apt download groff
sudo apt download groff-base
sudo apt download grub-common
sudo apt download grub-pc
sudo apt download grub-pc-bin
sudo apt download grub2-common
sudo apt download gsettings-desktop-schemas
sudo apt download gsfonts
sudo apt download gsfonts-x11
sudo apt download gstreamer1.0-gl
sudo apt download gstreamer1.0-libav
sudo apt download gstreamer1.0-plugins-bad
sudo apt download gstreamer1.0-plugins-base
sudo apt download gstreamer1.0-plugins-good
sudo apt download gstreamer1.0-pulseaudio
sudo apt download gstreamer1.0-x
sudo apt download gtk-update-icon-cache
sudo apt download gtk2-engines
sudo apt download gtk2-engines-murrine
sudo apt download gtk2-engines-pixbuf
sudo apt download gtk2.0-examples
sudo apt download guile-2.2-libs
sudo apt download gvfs
sudo apt download gvfs-backends
sudo apt download gvfs-common
sudo apt download gvfs-daemons
sudo apt download gvfs-fuse
sudo apt download gvfs-libs
sudo apt download gzip
sudo apt download haveged
sudo apt download hdparm
sudo apt download hicolor-icon-theme
sudo apt download highlight
sudo apt download highlight-common
sudo apt download hostapd
sudo apt download hostname
sudo apt download hspell
sudo apt download htop
sudo apt download hunspell
sudo apt download hunspell-en-us
sudo apt download hunspell-hu
sudo apt download hunspell-se
sudo apt download i965-va-driver
sudo apt download iamerican
sudo apt download ibrazilian
sudo apt download ibritish
sudo apt download ibulgarian
sudo apt download ibus
sudo apt download ibus-clutter
sudo apt download ibus-gtk
sudo apt download ibus-gtk3
sudo apt download ibus-m17n
sudo apt download icatalan
sudo apt download iceweasel
sudo apt download icu-devtools
sudo apt download idanish
sudo apt download idutch
sudo apt download ienglish-common
sudo apt download ifplugd
sudo apt download ifrench-gut
sudo apt download ifupdown
sudo apt download ihungarian
sudo apt download ii
sudo apt download iitalian
sudo apt download ilithuanian
sudo apt download im-config
sudo apt download imagemagick
sudo apt download imagemagick-6-common
sudo apt download imagemagick-6.q16
sudo apt download info
sudo apt download ingerman
sudo apt download init
sudo apt download init-system-helpers
sudo apt download initramfs-tools
sudo apt download initramfs-tools-core
sudo apt download inorwegian
sudo apt download install-info
sudo apt download intel-media-va-driver
sudo apt download intel-microcode
sudo apt download intltool-debian
sudo apt download ipolish
sudo apt download iportuguese
sudo apt download iproute2
sudo apt download iptables
sudo apt download iputils-ping
sudo apt download irussian
sudo apt download isc-dhcp-client
sudo apt download isc-dhcp-common
sudo apt download isc-dhcp-server
sudo apt download iso-codes
sudo apt download ispanish
sudo apt download ispell
sudo apt download iswiss
sudo apt download itools
sudo apt download iucode-tool
sudo apt download iukrainian
sudo apt download iw
sudo apt download iwd
sudo apt download java-common
sudo apt download javascript-common
sudo apt download jq
sudo apt download kasumi
sudo apt download kbd
sudo apt download keyboard-configuration
sudo apt download khmerconverter
sudo apt download klibc-utils
sudo apt download kmod
sudo apt download konwert
sudo apt download konwert-filters
sudo apt download krb5-locales
sudo apt download lacheck
sudo apt download latex-cjk-all
sudo apt download latex-cjk-chinese
sudo apt download latex-cjk-chinese-arphic-bkai00mp
sudo apt download latex-cjk-chinese-arphic-bsmi00lp
sudo apt download latex-cjk-chinese-arphic-gbsn00lp
sudo apt download latex-cjk-chinese-arphic-gkai00mp
sudo apt download latex-cjk-common
sudo apt download latex-cjk-japanese
sudo apt download latex-cjk-japanese-wadalab
sudo apt download latex-cjk-korean
sudo apt download latex-cjk-thai
sudo apt download latexdiff
sudo apt download latexmk
sudo apt download lcdf-typetools
sudo apt download less
sudo apt download liba52-0.7.4
sudo apt download libaa1
sudo apt download libaacs0
sudo apt download libabw-0.1-1
sudo apt download libacl1
sudo apt download libactivation-java
sudo apt download libalgorithm-c3-perl
sudo apt download libalgorithm-diff-perl
sudo apt download libalgorithm-diff-xs-perl
sudo apt download libalgorithm-merge-perl
sudo apt download libamd2
sudo apt download libamtk-5-0
sudo apt download libamtk-5-common
sudo apt download libanthy1
sudo apt download libanthyinput0
sudo apt download libao-common
sudo apt download libao4
sudo apt download libaom0
sudo apt download libaopalliance-java
sudo apt download libapache-poi-java
sudo apt download libapache-pom-java
sudo apt download libapparmor1
sudo apt download libapt-inst2.0
sudo apt download libapt-pkg5.0
sudo apt download libarchive-cpio-perl
sudo apt download libarchive-zip-perl
sudo apt download libarchive13
sudo apt download libargon2-1
sudo apt download libargs4j-java
sudo apt download libaribb24-0
sudo apt download libart-2.0-2
sudo apt download libasan5
sudo apt download libasm-java
sudo apt download libasound2
sudo apt download libasound2-data
sudo apt download libasound2-plugins
sudo apt download libaspell15
sudo apt download libass9
sudo apt download libassuan0
sudo apt download libasyncns0
sudo apt download libatasmart4
sudo apt download libatinject-jsr330-api-java
sudo apt download libatk-bridge2.0-0
sudo apt download libatk-bridge2.0-dev
sudo apt download libatk-wrapper-java
sudo apt download libatk-wrapper-java-jni
sudo apt download libatk1.0-0
sudo apt download libatk1.0-data
sudo apt download libatk1.0-dev
sudo apt download libatk1.0-doc
sudo apt download libatk3.0-cil
sudo apt download libatkmm-1.6-1v5
sudo apt download libatomic1
sudo apt download libatspi2.0-0
sudo apt download libatspi2.0-dev
sudo apt download libattr1
sudo apt download libaudio2
sudo apt download libaudit-common
sudo apt download libaudit1
sudo apt download libauthen-sasl-perl
sudo apt download libautovivification-perl
sudo apt download libavahi-client3
sudo apt download libavahi-common-data
sudo apt download libavahi-common3
sudo apt download libavahi-glib1
sudo apt download libavahi-ui-gtk3-0
sudo apt download libavc1394-0
sudo apt download libavcodec58
sudo apt download libavfilter7
sudo apt download libavformat58
sudo apt download libavresample4
sudo apt download libavutil56
sudo apt download libayatana-appindicator3-1
sudo apt download libayatana-ido3-0.4-0
sudo apt download libayatana-indicator3-7
sudo apt download libb-hooks-endofscope-perl
sudo apt download libb-hooks-op-check-perl
sudo apt download libbabeltrace1
sudo apt download libbabl-0.1-0
sudo apt download libbase-java
sudo apt download libbasicusageenvironment1
sudo apt download libbcmail-java
sudo apt download libbcpkix-java
sudo apt download libbcprov-java
sudo apt download libbdplus0
sudo apt download libbind9-161
sudo apt download libbinutils
sudo apt download libblas3
sudo apt download libblkid-dev
sudo apt download libblkid1
sudo apt download libblockdev-crypto2
sudo apt download libblockdev-fs2
sudo apt download libblockdev-loop2
sudo apt download libblockdev-part-err2
sudo apt download libblockdev-part2
sudo apt download libblockdev-swap2
sudo apt download libblockdev-utils2
sudo apt download libblockdev2
sudo apt download libbluetooth3
sudo apt download libbluray2
sudo apt download libboost-atomic1.67.0
sudo apt download libboost-chrono1.67.0
sudo apt download libboost-date-time1.67.0
sudo apt download libboost-filesystem1.67.0
sudo apt download libboost-iostreams1.67.0
sudo apt download libboost-locale1.67.0
sudo apt download libboost-system1.67.0
sudo apt download libboost-thread1.67.0
sudo apt download libbrotli1
sudo apt download libbs2b0
sudo apt download libbsd0
sudo apt download libbsh-java
sudo apt download libbtparse1
sudo apt download libburn4
sudo apt download libbusiness-isbn-data-perl
sudo apt download libbusiness-isbn-perl
sudo apt download libbusiness-ismn-perl
sudo apt download libbusiness-issn-perl
sudo apt download libbz2-1.0
sudo apt download libc-ares2
sudo apt download libc-bin
sudo apt download libc-dev-bin
sudo apt download libc-l10n
sudo apt download libc6
sudo apt download libc6-dbg
sudo apt download libc6-dev
sudo apt download libcaca0
sudo apt download libcairo-gobject2
sudo apt download libcairo-script-interpreter2
sudo apt download libcairo1.10-cil
sudo apt download libcairo2
sudo apt download libcairo2-dev
sudo apt download libcairomm-1.0-1v5
sudo apt download libcamd2
sudo apt download libcanberra-gtk3-0
sudo apt download libcanberra-gtk3-module
sudo apt download libcanberra0
sudo apt download libcap-ng0
sudo apt download libcap2
sudo apt download libcap2-bin
sudo apt download libcc1-0
sudo apt download libccolamd2
sudo apt download libcddb2
sudo apt download libcdi-api-java
sudo apt download libcdio-cdda2
sudo apt download libcdio-paranoia2
sudo apt download libcdio18
sudo apt download libcdparanoia0
sudo apt download libcdr-0.1-1
sudo apt download libcglib-java
sudo apt download libcholmod3
sudo apt download libchromaprint1
sudo apt download libclass-accessor-perl
sudo apt download libclass-c3-perl
sudo apt download libclass-c3-xs-perl
sudo apt download libclass-data-inheritable-perl
sudo apt download libclass-factory-util-perl
sudo apt download libclass-inspector-perl
sudo apt download libclass-method-modifiers-perl
sudo apt download libclass-singleton-perl
sudo apt download libclass-xsaccessor-perl
sudo apt download libclucene-contribs1v5
sudo apt download libclucene-core1v5
sudo apt download libclutter-1.0-0
sudo apt download libclutter-1.0-common
sudo apt download libclutter-imcontext-0.1-0
sudo apt download libclutter-imcontext-0.1-bin
sudo apt download libcmis-0.5-5v5
sudo apt download libcodec2-0.8.1
sudo apt download libcodemodel-java
sudo apt download libcogl-common
sudo apt download libcogl-pango20
sudo apt download libcogl-path20
sudo apt download libcogl20
sudo apt download libcolamd2
sudo apt download libcolord2
sudo apt download libcom-err2
sudo apt download libcommons-cli-java
sudo apt download libcommons-codec-java
sudo apt download libcommons-collections3-java
sudo apt download libcommons-collections4-java
sudo apt download libcommons-compress-java
sudo apt download libcommons-io-java
sudo apt download libcommons-lang3-java
sudo apt download libcommons-logging-java
sudo apt download libcommons-math3-java
sudo apt download libcommons-parent-java
sudo apt download libcpupower1
sudo apt download libcroco3
sudo apt download libcryptsetup12
sudo apt download libcrystalhd3
sudo apt download libctpl2
sudo apt download libcups2
sudo apt download libcupsfilters1
sudo apt download libcupsimage2
sudo apt download libcurl3-gnutls
sudo apt download libcurl4
sudo apt download libcurvesapi-java
sudo apt download libdaemon0
sudo apt download libdata-compare-perl
sudo apt download libdata-dump-perl
sudo apt download libdata-optlist-perl
sudo apt download libdata-uniqid-perl
sudo apt download libdate-simple-perl
sudo apt download libdatetime-calendar-julian-perl
sudo apt download libdatetime-format-builder-perl
sudo apt download libdatetime-format-strptime-perl
sudo apt download libdatetime-locale-perl
sudo apt download libdatetime-perl
sudo apt download libdatetime-timezone-perl
sudo apt download libdatrie1
sudo apt download libdb5.3
sudo apt download libdbus-1-3
sudo apt download libdbus-1-dev
sudo apt download libdbus-glib-1-2
sudo apt download libdbusmenu-glib4
sudo apt download libdbusmenu-gtk3-4
sudo apt download libdc1394-22
sudo apt download libdca0
sudo apt download libdconf1
sudo apt download libde265-0
sudo apt download libdebconfclient0
sudo apt download libdevel-callchecker-perl
sudo apt download libdevel-caller-perl
sudo apt download libdevel-globaldestruction-perl
sudo apt download libdevel-lexalias-perl
sudo apt download libdevel-stacktrace-perl
sudo apt download libdevhelp-3-6
sudo apt download libdevmapper1.02.1
sudo apt download libdirectfb-1.7-7
sudo apt download libdist-checkconflicts-perl
sudo apt download libdjvulibre-text
sudo apt download libdjvulibre21
sudo apt download libdns-export1104
sudo apt download libdns1104
sudo apt download libdom4j-java
sudo apt download libdouble-conversion1
sudo apt download libdpkg-perl
sudo apt download libdrm-amdgpu1
sudo apt download libdrm-common
sudo apt download libdrm-dev
sudo apt download libdrm-intel1
sudo apt download libdrm-nouveau2
sudo apt download libdrm-radeon1
sudo apt download libdrm2
sudo apt download libdtd-parser-java
sudo apt download libdv4
sudo apt download libdvbpsi10
sudo apt download libdvd-pkg
sudo apt download libdvdnav4
sudo apt download libdvdread4
sudo apt download libdw1
sudo apt download libdynaloader-functions-perl
sudo apt download libe-book-0.1-1
sudo apt download libebml4v5
sudo apt download libedit2
sudo apt download libefiboot1
sudo apt download libefivar1
sudo apt download libegl-mesa0
sudo apt download libegl1
sudo apt download libegl1-mesa
sudo apt download libegl1-mesa-dev
sudo apt download libehcache-java
sudo apt download libel-api-java
sudo apt download libelf1
sudo apt download libell0
sudo apt download libemail-date-format-perl
sudo apt download libemf1
sudo apt download libenca0
sudo apt download libenchant-voikko
sudo apt download libenchant1c2a
sudo apt download libencode-eucjpms-perl
sudo apt download libencode-hanextra-perl
sudo apt download libencode-jis2k-perl
sudo apt download libencode-locale-perl
sudo apt download libeot0
sudo apt download libepoxy-dev
sudo apt download libepoxy0
sudo apt download libepubgen-0.1-1
sudo apt download liberror-perl
sudo apt download libestr0
sudo apt download libetonyek-0.1-1
sudo apt download libev4
sudo apt download libeval-closure-perl
sudo apt download libevdev2
sudo apt download libevent-2.1-6
sudo apt download libevent-core-2.1-6
sudo apt download libevent-pthreads-2.1-6
sudo apt download libexception-class-perl
sudo apt download libexif12
sudo apt download libexiv2-14
sudo apt download libexo-1-0
sudo apt download libexo-2-0
sudo apt download libexo-common
sudo apt download libexo-helpers
sudo apt download libexpat1
sudo apt download libexpat1-dev
sudo apt download libexporter-tiny-perl
sudo apt download libext2fs2
sudo apt download libexttextcat-2.0-0
sudo apt download libexttextcat-data
sudo apt download libfaad2
sudo apt download libfakeroot
sudo apt download libfastinfoset-java
sudo apt download libfastjson4
sudo apt download libfbclient2
sudo apt download libfdisk1
sudo apt download libffi-dev
sudo apt download libffi6
sudo apt download libffmpegthumbnailer4v5
sudo apt download libfftw3-double3
sudo apt download libfftw3-single3
sudo apt download libfile-basedir-perl
sudo apt download libfile-desktopentry-perl
sudo apt download libfile-fcntllock-perl
sudo apt download libfile-find-rule-perl
sudo apt download libfile-homedir-perl
sudo apt download libfile-listing-perl
sudo apt download libfile-mimeinfo-perl
sudo apt download libfile-sharedir-perl
sudo apt download libfile-slurper-perl
sudo apt download libfile-stripnondeterminism-perl
sudo apt download libfile-which-perl
sudo apt download libflac8
sudo apt download libflite1
sudo apt download libfltk1.1
sudo apt download libfluidsynth1
sudo apt download libflute-java
sudo apt download libfm-data
sudo apt download libfm-extra4
sudo apt download libfm-gtk-data
sudo apt download libfm-gtk4
sudo apt download libfm-modules
sudo apt download libfm-tools
sudo apt download libfm4
sudo apt download libfont-afm-perl
sudo apt download libfontconfig1
sudo apt download libfontconfig1-dev
sudo apt download libfontenc1
sudo apt download libfonts-java
sudo apt download libformula-java
sudo apt download libfreehand-0.1-1
sudo apt download libfreetype6
sudo apt download libfreetype6-dev
sudo apt download libfribidi-dev
sudo apt download libfribidi0
sudo apt download libfsplib0
sudo apt download libfstrm0
sudo apt download libfuse2
sudo apt download libgail-common
sudo apt download libgail18
sudo apt download libgbm1
sudo apt download libgc1c2
sudo apt download libgcc-8-dev
sudo apt download libgcc1
sudo apt download libgck-1-0
sudo apt download libgck-1-dev
sudo apt download libgcr-3-dev
sudo apt download libgcr-base-3-1
sudo apt download libgcr-ui-3-1
sudo apt download libgcroots0
sudo apt download libgcrypt20
sudo apt download libgd3
sudo apt download libgdata-common
sudo apt download libgdata22
sudo apt download libgdbm-compat4
sudo apt download libgdbm6
sudo apt download libgdiplus
sudo apt download libgdk-pixbuf2.0-0
sudo apt download libgdk-pixbuf2.0-bin
sudo apt download libgdk-pixbuf2.0-common
sudo apt download libgdk-pixbuf2.0-dev
sudo apt download libgdk3.0-cil
sudo apt download libgdk3.0-cil-dev
sudo apt download libgegl-0.4-0
sudo apt download libgegl-common
sudo apt download libgeoip1
sudo apt download libgeronimo-annotation-1.3-spec-java
sudo apt download libgeronimo-interceptor-3.0-spec-java
sudo apt download libgexiv2-2
sudo apt download libgfortran5
sudo apt download libgif7
sudo apt download libgimp2.0
sudo apt download libgio3.0-cil
sudo apt download libgio3.0-cil-dev
sudo apt download libgirara-gtk3-3
sudo apt download libgirepository-1.0-1
sudo apt download libgit2-27
sudo apt download libgl1
sudo apt download libgl1-mesa-dev
sudo apt download libgl1-mesa-dri
sudo apt download libgladeui-2-6
sudo apt download libgladeui-common
sudo apt download libglapi-mesa
sudo apt download libgles1
sudo apt download libgles2
sudo apt download libglib2.0-0
sudo apt download libglib2.0-bin
sudo apt download libglib2.0-cil
sudo apt download libglib2.0-cil-dev
sudo apt download libglib2.0-data
sudo apt download libglib2.0-dev
sudo apt download libglib2.0-dev-bin
sudo apt download libglib2.0-doc
sudo apt download libglib3.0-cil
sudo apt download libglib3.0-cil-dev
sudo apt download libglibmm-2.4-1v5
sudo apt download libglu1-mesa
sudo apt download libglu1-mesa-dev
sudo apt download libglvnd-core-dev
sudo apt download libglvnd-dev
sudo apt download libglvnd0
sudo apt download libglx-mesa0
sudo apt download libglx0
sudo apt download libgme0
sudo apt download libgmp10
sudo apt download libgnutls-dane0
sudo apt download libgnutls30
sudo apt download libgoa-1.0-0b
sudo apt download libgoa-1.0-common
sudo apt download libgomp1
sudo apt download libgpg-error0
sudo apt download libgpgme11
sudo apt download libgpgmepp6
sudo apt download libgphoto2-6
sudo apt download libgphoto2-l10n
sudo apt download libgphoto2-port12
sudo apt download libgpm2
sudo apt download libgraphene-1.0-0
sudo apt download libgraphite2-3
sudo apt download libgraphite2-dev
sudo apt download libgroupsock8
sudo apt download libgs9
sudo apt download libgs9-common
sudo apt download libgsasl7
sudo apt download libgsl23
sudo apt download libgslcblas0
sudo apt download libgsm1
sudo apt download libgssapi-krb5-2
sudo apt download libgssdp-1.0-3
sudo apt download libgstreamer-gl1.0-0
sudo apt download libgstreamer-plugins-bad1.0-0
sudo apt download libgstreamer-plugins-base1.0-0
sudo apt download libgstreamer1.0-0
sudo apt download libgtk-3-0
sudo apt download libgtk-3-bin
sudo apt download libgtk-3-common
sudo apt download libgtk-3-dev
sudo apt download libgtk-3-doc
sudo apt download libgtk2.0-0
sudo apt download libgtk2.0-bin
sudo apt download libgtk2.0-cil
sudo apt download libgtk2.0-cil-dev
sudo apt download libgtk2.0-common
sudo apt download libgtk2.0-dev
sudo apt download libgtk2.0-doc
sudo apt download libgtk3.0-cil
sudo apt download libgtk3.0-cil-dev
sudo apt download libgtkmm-2.4-1v5
sudo apt download libgtkmm-3.0-1v5
sudo apt download libgtksourceview-3.0-1
sudo apt download libgtksourceview-3.0-common
sudo apt download libgtkspell3-3-0
sudo apt download libguava-java
sudo apt download libgudev-1.0-0
sudo apt download libguice-java
sudo apt download libgupnp-1.0-4
sudo apt download libgupnp-igd-1.0-4
sudo apt download libgwengui-gtk3-0
sudo apt download libgwenhywfar-data
sudo apt download libgwenhywfar60
sudo apt download libharfbuzz-dev
sudo apt download libharfbuzz-gobject0
sudo apt download libharfbuzz-icu0
sudo apt download libharfbuzz0b
sudo apt download libhavege1
sudo apt download libhawtjni-runtime-java
sudo apt download libhdate1
sudo apt download libheif1
sudo apt download libhfstospell10
sudo apt download libhogweed4
sudo apt download libhsqldb1.8.0-java
sudo apt download libhtml-form-perl
sudo apt download libhtml-format-perl
sudo apt download libhtml-parser-perl
sudo apt download libhtml-tagset-perl
sudo apt download libhtml-tree-perl
sudo apt download libhttp-cookies-perl
sudo apt download libhttp-daemon-perl
sudo apt download libhttp-date-perl
sudo apt download libhttp-message-perl
sudo apt download libhttp-negotiate-perl
sudo apt download libhttp-parser2.8
sudo apt download libhttpclient-java
sudo apt download libhttpcore-java
sudo apt download libhunspell-1.7-0
sudo apt download libhyphen0
sudo apt download libib-util
sudo apt download libibus-1.0-5
sudo apt download libice-dev
sudo apt download libice6
sudo apt download libicu-dev
sudo apt download libicu4j-java
sudo apt download libicu63
sudo apt download libid3tag0
sudo apt download libidn11
sudo apt download libidn2-0
sudo apt download libiec61883-0
sudo apt download libigdgmm5
sudo apt download libijs-0.35
sudo apt download libilmbase23
sudo apt download libimlib2
sudo apt download libimobiledevice6
sudo apt download libinput-bin
sudo apt download libinput10
sudo apt download libintellij-annotations-java
sudo apt download libio-html-perl
sudo apt download libio-socket-ssl-perl
sudo apt download libio-stringy-perl
sudo apt download libip4tc0
sudo apt download libip6tc0
sudo apt download libipc-run3-perl
sudo apt download libipc-shareable-perl
sudo apt download libipc-system-simple-perl
sudo apt download libipt2
sudo apt download libiptc0
sudo apt download libirs-export161
sudo apt download libisc-export1100
sudo apt download libisc1100
sudo apt download libisccc161
sudo apt download libisccfg-export163
sudo apt download libisccfg163
sudo apt download libisl19
sudo apt download libisofs6
sudo apt download libistack-commons-java
sudo apt download libitext-java
sudo apt download libitl0
sudo apt download libitm1
sudo apt download libiw30
sudo apt download libixml10
sudo apt download libjack-jackd2-0
sudo apt download libjansi-java
sudo apt download libjansi-native-java
sudo apt download libjansson4
sudo apt download libjavascriptcoregtk-4.0-18
sudo apt download libjaxb-api-java
sudo apt download libjaxb-java
sudo apt download libjaxen-java
sudo apt download libjbig0
sudo apt download libjbig2dec0
sudo apt download libjcommon-java
sudo apt download libjdom1-java
sudo apt download libjetbrains-annotations-java
sudo apt download libjim0.77
sudo apt download libjpeg-turbo-progs
sudo apt download libjpeg62-turbo
sudo apt download libjq1
sudo apt download libjs-jquery
sudo apt download libjs-sphinxdoc
sudo apt download libjs-underscore
sudo apt download libjs-xmlextras
sudo apt download libjson-c-dev
sudo apt download libjson-c3
sudo apt download libjson-glib-1.0-0
sudo apt download libjson-glib-1.0-common
sudo apt download libjsoup-java
sudo apt download libjsp-api-java
sudo apt download libjsr305-java
sudo apt download libjte1
sudo apt download libjxr-tools
sudo apt download libjxr0
sudo apt download libk5crypto3
sudo apt download libkate1
sudo apt download libkeyutils1
sudo apt download libkf5networkmanagerqt6
sudo apt download libklibc
sudo apt download libkmod2
sudo apt download libkpathsea6
sudo apt download libkrb5-3
sudo apt download libkrb5support0
sudo apt download libksba8
sudo apt download libkyotocabinet16v5
sudo apt download liblangtag-common
sudo apt download liblangtag1
sudo apt download liblapack3
sudo apt download liblayout-java
sudo apt download liblcms2-2
sudo apt download libldap-2.4-2
sudo apt download libldap-common
sudo apt download libldb1
sudo apt download liblilv-0-0
sudo apt download liblingua-translit-perl
sudo apt download liblirc-client0
sudo apt download liblist-allutils-perl
sudo apt download liblist-moreutils-perl
sudo apt download liblist-someutils-perl
sudo apt download liblist-utilsby-perl
sudo apt download liblivemedia64
sudo apt download libllvm7
sudo apt download liblmdb0
sudo apt download libloader-java
sudo apt download liblocale-gettext-perl
sudo apt download liblockfile-bin
sudo apt download liblog-dispatch-perl
sudo apt download liblog-log4perl-perl
sudo apt download liblog4j1.2-java
sudo apt download liblognorm5
sudo apt download liblqr-1-0
sudo apt download liblsan0
sudo apt download libltdl-dev
sudo apt download libltdl7
sudo apt download liblua5.1-0
sudo apt download liblua5.2-0
sudo apt download liblua5.3-0
sudo apt download liblwp-mediatypes-perl
sudo apt download liblwp-protocol-https-perl
sudo apt download liblwres161
sudo apt download liblz4-1
sudo apt download liblzma5
sudo apt download liblzo2-2
sudo apt download libm17n-0
sudo apt download libmad0
sudo apt download libmagic-mgc
sudo apt download libmagic1
sudo apt download libmagick++-6.q16-8
sudo apt download libmagickcore-6.q16-6
sudo apt download libmagickcore-6.q16-6-extra
sudo apt download libmagickwand-6.q16-6
sudo apt download libmail-java
sudo apt download libmail-sendmail-perl
sudo apt download libmailtools-perl
sudo apt download libmailutils5
sudo apt download libmariadb3
sudo apt download libmatroska6v5
sudo apt download libmaven-file-management-java
sudo apt download libmaven-parent-java
sudo apt download libmaven-resolver-java
sudo apt download libmaven-shared-io-java
sudo apt download libmaven-shared-utils-java
sudo apt download libmaven3-core-java
sudo apt download libmbedcrypto3
sudo apt download libmbedtls12
sudo apt download libmbedx509-0
sudo apt download libmbim-glib4
sudo apt download libmbim-proxy
sudo apt download libmenu-cache-bin
sudo apt download libmenu-cache3
sudo apt download libmetis5
sudo apt download libmhash2
sudo apt download libmime-charset-perl
sudo apt download libmime-lite-perl
sudo apt download libmime-types-perl
sudo apt download libmjpegutils-2.1-0
sudo apt download libmm-glib0
sudo apt download libmms0
sudo apt download libmng1
sudo apt download libmnl0
sudo apt download libmodplug1
sudo apt download libmodule-implementation-perl
sudo apt download libmodule-runtime-perl
sudo apt download libmono-2.0-dev
sudo apt download libmono-accessibility4.0-cil
sudo apt download libmono-btls-interface4.0-cil
sudo apt download libmono-cairo4.0-cil
sudo apt download libmono-cecil-private-cil
sudo apt download libmono-cil-dev
sudo apt download libmono-codecontracts4.0-cil
sudo apt download libmono-compilerservices-symbolwriter4.0-cil
sudo apt download libmono-corlib4.5-cil
sudo apt download libmono-cscompmgd0.0-cil
sudo apt download libmono-csharp4.0c-cil
sudo apt download libmono-custommarshalers4.0-cil
sudo apt download libmono-data-tds4.0-cil
sudo apt download libmono-db2-1.0-cil
sudo apt download libmono-debugger-soft4.0a-cil
sudo apt download libmono-http4.0-cil
sudo apt download libmono-i18n-cjk4.0-cil
sudo apt download libmono-i18n-mideast4.0-cil
sudo apt download libmono-i18n-other4.0-cil
sudo apt download libmono-i18n-rare4.0-cil
sudo apt download libmono-i18n-west4.0-cil
sudo apt download libmono-i18n4.0-all
sudo apt download libmono-i18n4.0-cil
sudo apt download libmono-ldap4.0-cil
sudo apt download libmono-management4.0-cil
sudo apt download libmono-messaging-rabbitmq4.0-cil
sudo apt download libmono-messaging4.0-cil
sudo apt download libmono-microsoft-build-engine4.0-cil
sudo apt download libmono-microsoft-build-framework4.0-cil
sudo apt download libmono-microsoft-build-tasks-v4.0-4.0-cil
sudo apt download libmono-microsoft-build-utilities-v4.0-4.0-cil
sudo apt download libmono-microsoft-build4.0-cil
sudo apt download libmono-microsoft-csharp4.0-cil
sudo apt download libmono-microsoft-visualc10.0-cil
sudo apt download libmono-microsoft-web-infrastructure1.0-cil
sudo apt download libmono-oracle4.0-cil
sudo apt download libmono-parallel4.0-cil
sudo apt download libmono-peapi4.0a-cil
sudo apt download libmono-posix4.0-cil
sudo apt download libmono-profiler-gui-thread-check
sudo apt download libmono-rabbitmq4.0-cil
sudo apt download libmono-relaxng4.0-cil
sudo apt download libmono-security4.0-cil
sudo apt download libmono-sharpzip4.84-cil
sudo apt download libmono-simd4.0-cil
sudo apt download libmono-smdiagnostics0.0-cil
sudo apt download libmono-sqlite4.0-cil
sudo apt download libmono-system-componentmodel-composition4.0-cil
sudo apt download libmono-system-componentmodel-dataannotations4.0-cil
sudo apt download libmono-system-configuration-install4.0-cil
sudo apt download libmono-system-configuration4.0-cil
sudo apt download libmono-system-core4.0-cil
sudo apt download libmono-system-data-datasetextensions4.0-cil
sudo apt download libmono-system-data-entity4.0-cil
sudo apt download libmono-system-data-linq4.0-cil
sudo apt download libmono-system-data-services-client4.0-cil
sudo apt download libmono-system-data-services4.0-cil
sudo apt download libmono-system-data4.0-cil
sudo apt download libmono-system-deployment4.0-cil
sudo apt download libmono-system-design4.0-cil
sudo apt download libmono-system-drawing-design4.0-cil
sudo apt download libmono-system-drawing4.0-cil
sudo apt download libmono-system-dynamic4.0-cil
sudo apt download libmono-system-enterpriseservices4.0-cil
sudo apt download libmono-system-identitymodel-selectors4.0-cil
sudo apt download libmono-system-identitymodel4.0-cil
sudo apt download libmono-system-io-compression-filesystem4.0-cil
sudo apt download libmono-system-io-compression4.0-cil
sudo apt download libmono-system-json-microsoft4.0-cil
sudo apt download libmono-system-json4.0-cil
sudo apt download libmono-system-ldap-protocols4.0-cil
sudo apt download libmono-system-ldap4.0-cil
sudo apt download libmono-system-management4.0-cil
sudo apt download libmono-system-messaging4.0-cil
sudo apt download libmono-system-net-http-formatting4.0-cil
sudo apt download libmono-system-net-http-webrequest4.0-cil
sudo apt download libmono-system-net-http4.0-cil
sudo apt download libmono-system-net4.0-cil
sudo apt download libmono-system-numerics-vectors4.0-cil
sudo apt download libmono-system-numerics4.0-cil
sudo apt download libmono-system-reactive-core2.2-cil
sudo apt download libmono-system-reactive-debugger2.2-cil
sudo apt download libmono-system-reactive-experimental2.2-cil
sudo apt download libmono-system-reactive-interfaces2.2-cil
sudo apt download libmono-system-reactive-linq2.2-cil
sudo apt download libmono-system-reactive-observable-aliases0.0-cil
sudo apt download libmono-system-reactive-platformservices2.2-cil
sudo apt download libmono-system-reactive-providers2.2-cil
sudo apt download libmono-system-reactive-runtime-remoting2.2-cil
sudo apt download libmono-system-reactive-windows-forms2.2-cil
sudo apt download libmono-system-reactive-windows-threading2.2-cil
sudo apt download libmono-system-reflection-context4.0-cil
sudo apt download libmono-system-runtime-caching4.0-cil
sudo apt download libmono-system-runtime-durableinstancing4.0-cil
sudo apt download libmono-system-runtime-serialization-formatters-soap4.0-cil
sudo apt download libmono-system-runtime-serialization4.0-cil
sudo apt download libmono-system-runtime4.0-cil
sudo apt download libmono-system-security4.0-cil
sudo apt download libmono-system-servicemodel-activation4.0-cil
sudo apt download libmono-system-servicemodel-discovery4.0-cil
sudo apt download libmono-system-servicemodel-internals0.0-cil
sudo apt download libmono-system-servicemodel-routing4.0-cil
sudo apt download libmono-system-servicemodel-web4.0-cil
sudo apt download libmono-system-servicemodel4.0a-cil
sudo apt download libmono-system-serviceprocess4.0-cil
sudo apt download libmono-system-threading-tasks-dataflow4.0-cil
sudo apt download libmono-system-transactions4.0-cil
sudo apt download libmono-system-web-abstractions4.0-cil
sudo apt download libmono-system-web-applicationservices4.0-cil
sudo apt download libmono-system-web-dynamicdata4.0-cil
sudo apt download libmono-system-web-extensions-design4.0-cil
sudo apt download libmono-system-web-extensions4.0-cil
sudo apt download libmono-system-web-http-selfhost4.0-cil
sudo apt download libmono-system-web-http-webhost4.0-cil
sudo apt download libmono-system-web-http4.0-cil
sudo apt download libmono-system-web-mobile4.0-cil
sudo apt download libmono-system-web-mvc3.0-cil
sudo apt download libmono-system-web-razor2.0-cil
sudo apt download libmono-system-web-regularexpressions4.0-cil
sudo apt download libmono-system-web-routing4.0-cil
sudo apt download libmono-system-web-services4.0-cil
sudo apt download libmono-system-web-webpages-deployment2.0-cil
sudo apt download libmono-system-web-webpages-razor2.0-cil
sudo apt download libmono-system-web-webpages2.0-cil
sudo apt download libmono-system-web4.0-cil
sudo apt download libmono-system-windows-forms-datavisualization4.0a-cil
sudo apt download libmono-system-windows-forms4.0-cil
sudo apt download libmono-system-windows4.0-cil
sudo apt download libmono-system-workflow-activities4.0-cil
sudo apt download libmono-system-workflow-componentmodel4.0-cil
sudo apt download libmono-system-workflow-runtime4.0-cil
sudo apt download libmono-system-xaml4.0-cil
sudo apt download libmono-system-xml-linq4.0-cil
sudo apt download libmono-system-xml-serialization4.0-cil
sudo apt download libmono-system-xml4.0-cil
sudo apt download libmono-system4.0-cil
sudo apt download libmono-tasklets4.0-cil
sudo apt download libmono-webbrowser4.0-cil
sudo apt download libmono-webmatrix-data4.0-cil
sudo apt download libmono-windowsbase4.0-cil
sudo apt download libmono-xbuild-tasks4.0-cil
sudo apt download libmonosgen-2.0-1
sudo apt download libmonosgen-2.0-dev
sudo apt download libmount-dev
sudo apt download libmount1
sudo apt download libmp3lame0
sudo apt download libmpc3
sudo apt download libmpcdec6
sudo apt download libmpdec2
sudo apt download libmpeg2-4
sudo apt download libmpeg2encpp-2.1-0
sudo apt download libmpfr6
sudo apt download libmpg123-0
sudo apt download libmplex2-2.1-0
sudo apt download libmpx2
sudo apt download libmro-compat-perl
sudo apt download libmspub-0.1-1
sudo apt download libmtdev1
sudo apt download libmtp-common
sudo apt download libmtp-runtime
sudo apt download libmtp9
sudo apt download libmwaw-0.3-3
sudo apt download libmypaint-1.3-0
sudo apt download libmypaint-common
sudo apt download libmysofa0
sudo apt download libmythes-1.2-0
sudo apt download libnamespace-autoclean-perl
sudo apt download libnamespace-clean-perl
sudo apt download libncurses6
sudo apt download libncursesw6
sudo apt download libndp0
sudo apt download libneon27-gnutls
sudo apt download libnet-dbus-perl
sudo apt download libnet-http-perl
sudo apt download libnet-smtp-ssl-perl
sudo apt download libnet-ssleay-perl
sudo apt download libnetfilter-conntrack3
sudo apt download libnetpbm10
sudo apt download libnettle6
sudo apt download libnewt0.52
sudo apt download libnfnetlink0
sudo apt download libnfs12
sudo apt download libnftables0
sudo apt download libnftnl11
sudo apt download libnghttp2-14
sudo apt download libnice10
sudo apt download libnl-3-200
sudo apt download libnl-genl-3-200
sudo apt download libnl-route-3-200
sudo apt download libnm0
sudo apt download libnma0
sudo apt download libnode64
sudo apt download libnorm1
sudo apt download libnotify4
sudo apt download libnpth0
sudo apt download libnspr4
sudo apt download libnss-myhostname
sudo apt download libnss-systemd
sudo apt download libnss3
sudo apt download libntfs-3g883
sudo apt download libntlm0
sudo apt download libnuma1
sudo apt download libnumber-compare-perl
sudo apt download libnumbertext-1.0-0
sudo apt download libnumbertext-data
sudo apt download libnunit-cil-dev
sudo apt download libnunit-console-runner2.6.3-cil
sudo apt download libnunit-core-interfaces2.6.3-cil
sudo apt download libnunit-core2.6.3-cil
sudo apt download libnunit-framework2.6.3-cil
sudo apt download libnunit-mocks2.6.3-cil
sudo apt download libnunit-util2.6.3-cil
sudo apt download liboauth0
sudo apt download libobrender32v5
sudo apt download libobt2v5
sudo apt download libodfgen-0.1-1
sudo apt download libofa0
sudo apt download libogg0
sudo apt download libonig5
sudo apt download libopenal-data
sudo apt download libopenal1
sudo apt download libopencc2
sudo apt download libopencc2-data
sudo apt download libopenexr23
sudo apt download libopengl0
sudo apt download libopenjp2-7
sudo apt download libopenmpt-modplug1
sudo apt download libopenmpt0
sudo apt download libopts25
sudo apt download libopus0
sudo apt download liborc-0.4-0
sudo apt download liborcus-0.14-0
sudo apt download libosmesa6
sudo apt download libosp5
sudo apt download libostyle1c2
sudo apt download libotf0
sudo apt download libp11-kit-dev
sudo apt download libp11-kit0
sudo apt download libpackage-stash-perl
sudo apt download libpackage-stash-xs-perl
sudo apt download libpadwalker-perl
sudo apt download libpagemaker-0.0-0
sudo apt download libpam-gnome-keyring
sudo apt download libpam-modules
sudo apt download libpam-modules-bin
sudo apt download libpam-runtime
sudo apt download libpam-systemd
sudo apt download libpam0g
sudo apt download libpango-1.0-0
sudo apt download libpango1.0-dev
sudo apt download libpango1.0-doc
sudo apt download libpango3.0-cil
sudo apt download libpangocairo-1.0-0
sudo apt download libpangoft2-1.0-0
sudo apt download libpangomm-1.4-1v5
sudo apt download libpangoxft-1.0-0
sudo apt download libpaper-utils
sudo apt download libpaper1
sudo apt download libparams-classify-perl
sudo apt download libparams-util-perl
sudo apt download libparams-validate-perl
sudo apt download libparams-validationcompiler-perl
sudo apt download libparted-fs-resize0
sudo apt download libparted2
sudo apt download libpcap0.8
sudo apt download libpci3
sudo apt download libpciaccess0
sudo apt download libpcre16-3
sudo apt download libpcre2-16-0
sudo apt download libpcre2-8-0
sudo apt download libpcre3
sudo apt download libpcre3-dev
sudo apt download libpcre32-3
sudo apt download libpcrecpp0v5
sudo apt download libpcsclite1
sudo apt download libpentaho-reporting-flow-engine-java
sudo apt download libperl5.28
sudo apt download libperlio-utf8-strict-perl
sudo apt download libpgm-5.2-0
sudo apt download libpipeline1
sudo apt download libpixie-java
sudo apt download libpixman-1-0
sudo apt download libpixman-1-dev
sudo apt download libplacebo7
sudo apt download libplexus-archiver-java
sudo apt download libplexus-cipher-java
sudo apt download libplexus-classworlds-java
sudo apt download libplexus-component-annotations-java
sudo apt download libplexus-interpolation-java
sudo apt download libplexus-io-java
sudo apt download libplexus-sec-dispatcher-java
sudo apt download libplexus-utils2-java
sudo apt download libplist3
sudo apt download libplot2c2
sudo apt download libpng-dev
sudo apt download libpng-tools
sudo apt download libpng16-16
sudo apt download libpolkit-agent-1-0
sudo apt download libpolkit-backend-1-0
sudo apt download libpolkit-gobject-1-0
sudo apt download libpoppler-glib8
sudo apt download libpoppler-qt5-1
sudo apt download libpoppler82
sudo apt download libpopt0
sudo apt download libpostproc55
sudo apt download libpotrace0
sudo apt download libpq5
sudo apt download libprocps7
sudo apt download libprotobuf-c1
sudo apt download libprotobuf-lite17
sudo apt download libproxy-tools
sudo apt download libproxy1v5
sudo apt download libpsl5
sudo apt download libpstoedit0c2a
sudo apt download libptexenc1
sudo apt download libpth20
sudo apt download libpthread-stubs0-dev
sudo apt download libpulse-mainloop-glib0
sudo apt download libpulse0
sudo apt download libpulsedsp
sudo apt download libpython-all-dev
sudo apt download libpython-dev
sudo apt download libpython-stdlib
sudo apt download libpython2-dev
sudo apt download libpython2-stdlib
sudo apt download libpython2.7
sudo apt download libpython2.7-dev
sudo apt download libpython2.7-minimal
sudo apt download libpython2.7-stdlib
sudo apt download libpython3-dev
sudo apt download libpython3-stdlib
sudo apt download libpython3.7
sudo apt download libpython3.7-dev
sudo apt download libpython3.7-minimal
sudo apt download libpython3.7-stdlib
sudo apt download libqalculate20
sudo apt download libqalculate20-data
sudo apt download libqmi-glib5
sudo apt download libqmi-proxy
sudo apt download libqt5concurrent5
sudo apt download libqt5core5a
sudo apt download libqt5dbus5
sudo apt download libqt5designer5
sudo apt download libqt5gui5
sudo apt download libqt5help5
sudo apt download libqt5network5
sudo apt download libqt5printsupport5
sudo apt download libqt5script5
sudo apt download libqt5sql5
sudo apt download libqt5sql5-sqlite
sudo apt download libqt5svg5
sudo apt download libqt5test5
sudo apt download libqt5widgets5
sudo apt download libqt5x11extras5
sudo apt download libqt5xml5
sudo apt download libquadmath0
sudo apt download libquazip5-1
sudo apt download libqxp-0.0-0
sudo apt download libraptor2-0
sudo apt download librasqal3
sudo apt download libraw1394-11
sudo apt download libraw19
sudo apt download librcc0
sudo apt download librccgtk2-0
sudo apt download librcd0
sudo apt download librdf0
sudo apt download libreadline7
sudo apt download libreadonly-perl
sudo apt download librecode0
sudo apt download libref-util-perl
sudo apt download libref-util-xs-perl
sudo apt download libregexp-common-perl
sudo apt download librelaxng-datatype-java
sudo apt download libreoffice
sudo apt download libreoffice-avmedia-backend-gstreamer
sudo apt download libreoffice-base
sudo apt download libreoffice-base-core
sudo apt download libreoffice-base-drivers
sudo apt download libreoffice-calc
sudo apt download libreoffice-common
sudo apt download libreoffice-core
sudo apt download libreoffice-draw
sudo apt download libreoffice-impress
sudo apt download libreoffice-java-common
sudo apt download libreoffice-librelogo
sudo apt download libreoffice-math
sudo apt download libreoffice-nlpsolver
sudo apt download libreoffice-report-builder
sudo apt download libreoffice-report-builder-bin
sudo apt download libreoffice-script-provider-bsh
sudo apt download libreoffice-script-provider-js
sudo apt download libreoffice-script-provider-python
sudo apt download libreoffice-sdbc-firebird
sudo apt download libreoffice-sdbc-hsqldb
sudo apt download libreoffice-sdbc-postgresql
sudo apt download libreoffice-style-colibre
sudo apt download libreoffice-style-tango
sudo apt download libreoffice-wiki-publisher
sudo apt download libreoffice-writer
sudo apt download librepository-java
sudo apt download libresid-builder0c2a
sudo apt download librest-0.7-0
sudo apt download librevenge-0.0-0
sudo apt download librngom-java
sudo apt download librole-tiny-perl
sudo apt download librsvg2-2
sudo apt download librsvg2-bin
sudo apt download librsvg2-common
sudo apt download librtmp1
sudo apt download librubberband2
sudo apt download libruby2.5
sudo apt download libsac-java
sudo apt download libsamplerate0
sudo apt download libsasl2-2
sudo apt download libsasl2-modules
sudo apt download libsasl2-modules-db
sudo apt download libsaxonhe-java
sudo apt download libsbc1
sudo apt download libsdl-image1.2
sudo apt download libsdl1.2debian
sudo apt download libseccomp2
sudo apt download libsecret-1-0
sudo apt download libsecret-common
sudo apt download libselinux1
sudo apt download libselinux1-dev
sudo apt download libsemanage-common
sudo apt download libsemanage1
sudo apt download libsensors-config
sudo apt download libsensors5
sudo apt download libsepol1
sudo apt download libsepol1-dev
sudo apt download libserd-0-0
sudo apt download libserializer-java
sudo apt download libservlet-api-java
sudo apt download libservlet3.1-java
sudo apt download libshine3
sudo apt download libshout3
sudo apt download libsidplay2
sudo apt download libsigc++-2.0-0v5
sudo apt download libsigsegv2
sudo apt download libsisu-guice-java
sudo apt download libsisu-inject-java
sudo apt download libsisu-ioc-java
sudo apt download libsisu-plexus-java
sudo apt download libslang2
sudo apt download libslf4j-java
sudo apt download libsm-dev
sudo apt download libsm6
sudo apt download libsmartcols1
sudo apt download libsmbclient
sudo apt download libsnappy-java
sudo apt download libsnappy-jni
sudo apt download libsnappy1v5
sudo apt download libsndfile1
sudo apt download libsndio7.0
sudo apt download libsodium23
sudo apt download libsombok3
sudo apt download libsord-0-0
sudo apt download libsort-key-perl
sudo apt download libsoundtouch1
sudo apt download libsoup-gnome2.4-1
sudo apt download libsoup2.4-1
sudo apt download libsoxr0
sudo apt download libspandsp2
sudo apt download libspatialaudio0
sudo apt download libspecio-perl
sudo apt download libspeex1
sudo apt download libspeexdsp1
sudo apt download libsqlite3-0
sudo apt download libsratom-0-0
sudo apt download libsrtp2-1
sudo apt download libss2
sudo apt download libssh-gcrypt-4
sudo apt download libssh2-1
sudo apt download libssl1.1
sudo apt download libstaroffice-0.0-0
sudo apt download libstartup-notification0
sudo apt download libstax-ex-java
sudo apt download libstdc++-8-dev
sudo apt download libstdc++6
sudo apt download libstreambuffer-java
sudo apt download libsub-exporter-perl
sudo apt download libsub-exporter-progressive-perl
sudo apt download libsub-identify-perl
sudo apt download libsub-install-perl
sudo apt download libsub-name-perl
sudo apt download libsub-quote-perl
sudo apt download libsuitesparseconfig5
sudo apt download libswresample3
sudo apt download libswscale5
sudo apt download libsynctex2
sudo apt download libsys-hostname-long-perl
sudo apt download libsystemd0
sudo apt download libtag1v5
sudo apt download libtag1v5-vanilla
sudo apt download libtagc0
sudo apt download libtalloc2
sudo apt download libtasn1-6
sudo apt download libtcl8.6
sudo apt download libtdb1
sudo apt download libteamdctl0
sudo apt download libteckit0
sudo apt download libtevent0
sudo apt download libtexlua52
sudo apt download libtexlua53
sudo apt download libtexluajit2
sudo apt download libtext-bibtex-perl
sudo apt download libtext-charwidth-perl
sudo apt download libtext-csv-perl
sudo apt download libtext-csv-xs-perl
sudo apt download libtext-glob-perl
sudo apt download libtext-iconv-perl
sudo apt download libtext-roman-perl
sudo apt download libtext-unidecode-perl
sudo apt download libtext-wrapi18n-perl
sudo apt download libthai-data
sudo apt download libthai0
sudo apt download libtheora0
sudo apt download libthunarx-3-0
sudo apt download libtie-cycle-perl
sudo apt download libtie-ixhash-perl
sudo apt download libtiff5
sudo apt download libtimedate-perl
sudo apt download libtinfo6
sudo apt download libtk8.6
sudo apt download libtommath1
sudo apt download libtool
sudo apt download libtre5
sudo apt download libtry-tiny-perl
sudo apt download libtsan0
sudo apt download libtumbler-1-0
sudo apt download libturbojpeg0
sudo apt download libtwolame0
sudo apt download libtxw2-java
sudo apt download libubsan1
sudo apt download libuchardet0
sudo apt download libudev1
sudo apt download libudisks2-0
sudo apt download libuim-custom2
sudo apt download libuim-data
sudo apt download libuim-scm0
sudo apt download libuim8
sudo apt download libumfpack5
sudo apt download libunbound8
sudo apt download libunicode-linebreak-perl
sudo apt download libunique-1.0-0
sudo apt download libunistring2
sudo apt download libunwind8
sudo apt download libupnp13
sudo apt download libupower-glib3
sudo apt download liburi-perl
sudo apt download libusageenvironment3
sudo apt download libusb-1.0-0
sudo apt download libusbmuxd-tools
sudo apt download libusbmuxd4
sudo apt download libutempter0
sudo apt download libuuid1
sudo apt download libuv1
sudo apt download libv4l-0
sudo apt download libv4lconvert0
sudo apt download libva-drm2
sudo apt download libva-wayland2
sudo apt download libva-x11-2
sudo apt download libva2
sudo apt download libvariable-magic-perl
sudo apt download libvdpau-va-gl1
sudo apt download libvdpau1
sudo apt download libvidstab1.1
sudo apt download libvisio-0.1-1
sudo apt download libvisual-0.4-0
sudo apt download libvlc-bin
sudo apt download libvlc5
sudo apt download libvlccore9
sudo apt download libvo-aacenc0
sudo apt download libvo-amrwbenc0
sudo apt download libvoikko1
sudo apt download libvolume-key1
sudo apt download libvorbis0a
sudo apt download libvorbisenc2
sudo apt download libvorbisfile3
sudo apt download libvorbisidec1
sudo apt download libvpx5
sudo apt download libvte-common
sudo apt download libvte-dev
sudo apt download libvte9
sudo apt download libvulkan1
sudo apt download libwacom-bin
sudo apt download libwacom-common
sudo apt download libwacom2
sudo apt download libwagon-http-java
sudo apt download libwagon-provider-api-java
sudo apt download libwavpack1
sudo apt download libwayland-bin
sudo apt download libwayland-client0
sudo apt download libwayland-cursor0
sudo apt download libwayland-dev
sudo apt download libwayland-egl1
sudo apt download libwayland-server0
sudo apt download libwbclient0
sudo apt download libwebkit2gtk-4.0-37
sudo apt download libwebp6
sudo apt download libwebpdemux2
sudo apt download libwebpmux3
sudo apt download libwebrtc-audio-processing1
sudo apt download libwebsocket-api-java
sudo apt download libwildmidi2
sudo apt download libwmf0.2-7
sudo apt download libwoff1
sudo apt download libwpd-0.10-10
sudo apt download libwpg-0.3-3
sudo apt download libwps-0.4-4
sudo apt download libwrap0
sudo apt download libwww-perl
sudo apt download libwww-robotrules-perl
sudo apt download libwxbase3.0-0v5
sudo apt download libwxbase3.0-dev
sudo apt download libwxgtk-media3.0-gtk3-0v5
sudo apt download libwxgtk-webview3.0-gtk3-0v5
sudo apt download libwxgtk3.0-0v5
sudo apt download libwxgtk3.0-dev
sudo apt download libwxgtk3.0-gtk3-0v5
sudo apt download libwxgtk3.0-gtk3-dev
sudo apt download libx11-6
sudo apt download libx11-data
sudo apt download libx11-dev
sudo apt download libx11-protocol-perl
sudo apt download libx11-xcb-dev
sudo apt download libx11-xcb1
sudo apt download libx264-155
sudo apt download libx265-165
sudo apt download libx86-1
sudo apt download libxatracker2
sudo apt download libxau-dev
sudo apt download libxau6
sudo apt download libxaw7
sudo apt download libxcb-dri2-0
sudo apt download libxcb-dri2-0-dev
sudo apt download libxcb-dri3-0
sudo apt download libxcb-dri3-dev
sudo apt download libxcb-glx0
sudo apt download libxcb-glx0-dev
sudo apt download libxcb-icccm4
sudo apt download libxcb-image0
sudo apt download libxcb-keysyms1
sudo apt download libxcb-present-dev
sudo apt download libxcb-present0
sudo apt download libxcb-randr0
sudo apt download libxcb-randr0-dev
sudo apt download libxcb-render-util0
sudo apt download libxcb-render0
sudo apt download libxcb-render0-dev
sudo apt download libxcb-shape0
sudo apt download libxcb-shape0-dev
sudo apt download libxcb-shm0
sudo apt download libxcb-shm0-dev
sudo apt download libxcb-sync-dev
sudo apt download libxcb-sync1
sudo apt download libxcb-util0
sudo apt download libxcb-xfixes0
sudo apt download libxcb-xfixes0-dev
sudo apt download libxcb-xinerama0
sudo apt download libxcb-xkb1
sudo apt download libxcb-xv0
sudo apt download libxcb1
sudo apt download libxcb1-dev
sudo apt download libxcomposite-dev
sudo apt download libxcomposite1
sudo apt download libxcursor-dev
sudo apt download libxcursor1
sudo apt download libxdamage-dev
sudo apt download libxdamage1
sudo apt download libxdmcp-dev
sudo apt download libxdmcp6
sudo apt download libxerces2-java
sudo apt download libxext-dev
sudo apt download libxext6
sudo apt download libxfce4panel-2.0-4
sudo apt download libxfce4ui-1-0
sudo apt download libxfce4ui-2-0
sudo apt download libxfce4ui-common
sudo apt download libxfce4util-bin
sudo apt download libxfce4util-common
sudo apt download libxfce4util7
sudo apt download libxfconf-0-2
sudo apt download libxfixes-dev
sudo apt download libxfixes3
sudo apt download libxfont2
sudo apt download libxft-dev
sudo apt download libxft2
sudo apt download libxi-dev
sudo apt download libxi6
sudo apt download libxinerama-dev
sudo apt download libxinerama1
sudo apt download libxkbcommon-dev
sudo apt download libxkbcommon-x11-0
sudo apt download libxkbcommon0
sudo apt download libxkbfile1
sudo apt download libxml-commons-external-java
sudo apt download libxml-commons-resolver1.1-java
sudo apt download libxml-java
sudo apt download libxml-libxml-perl
sudo apt download libxml-libxml-simple-perl
sudo apt download libxml-libxslt-perl
sudo apt download libxml-namespacesupport-perl
sudo apt download libxml-parser-perl
sudo apt download libxml-sax-base-perl
sudo apt download libxml-sax-expat-perl
sudo apt download libxml-sax-perl
sudo apt download libxml-twig-perl
sudo apt download libxml-writer-perl
sudo apt download libxml-xpathengine-perl
sudo apt download libxml2
sudo apt download libxml2-utils
sudo apt download libxmlbeans-java
sudo apt download libxmlsec1
sudo apt download libxmlsec1-nss
sudo apt download libxmu6
sudo apt download libxmuu1
sudo apt download libxom-java
sudo apt download libxpm4
sudo apt download libxrandr-dev
sudo apt download libxrandr2
sudo apt download libxrender-dev
sudo apt download libxrender1
sudo apt download libxshmfence-dev
sudo apt download libxshmfence1
sudo apt download libxslt1.1
sudo apt download libxsom-java
sudo apt download libxss1
sudo apt download libxt6
sudo apt download libxtables12
sudo apt download libxtst-dev
sudo apt download libxtst6
sudo apt download libxv1
sudo apt download libxvidcore4
sudo apt download libxvmc1
sudo apt download libxxf86dga1
sudo apt download libxxf86vm-dev
sudo apt download libxxf86vm1
sudo apt download libxxhash0
sudo apt download libxz-java
sudo apt download libyajl2
sudo apt download libyaml-0-2
sudo apt download libyaml-tiny-perl
sudo apt download libzbar0
sudo apt download libzip4
sudo apt download libzmf-0.0-0
sudo apt download libzmq5
sudo apt download libzstd1
sudo apt download libzvbi-common
sudo apt download libzvbi0
sudo apt download libzzip-0-13
sudo apt download linux-base
sudo apt download linux-compiler-gcc-8-x86
sudo apt download linux-cpupower
sudo apt download linux-headers-4.19.0-13-amd64
sudo apt download linux-headers-4.19.0-13-common
sudo apt download linux-headers-amd64
sudo apt download linux-image-4.19.0-13-amd64
sudo apt download linux-image-amd64
sudo apt download linux-kbuild-4.19
sudo apt download linux-libc-dev
sudo apt download live-task-localisation
sudo apt download live-task-recommended
sudo apt download lmodern
sudo apt download locales
sudo apt download login
sudo apt download logrotate
sudo apt download lp-solve
sudo apt download lsb-base
sudo apt download lsb-release
sudo apt download lsof
sudo apt download lv
sudo apt download lxappearance
sudo apt download lxde-icon-theme
sudo apt download lxde-settings-daemon
sudo apt download lxmenu-data
sudo apt download lxpolkit
sudo apt download lxsession-data
sudo apt download m17n-db
sudo apt download m4
sudo apt download mailutils
sudo apt download mailutils-common
sudo apt download maint-guide-it
sudo apt download make
sudo apt download man-db
sudo apt download manpages
sudo apt download manpages-de
sudo apt download manpages-dev
sudo apt download manpages-es
sudo apt download manpages-hu
sudo apt download manpages-it
sudo apt download manpages-ja
sudo apt download manpages-ja-dev
sudo apt download manpages-pl
sudo apt download manpages-pl-dev
sudo apt download manpages-pt
sudo apt download manpages-tr
sudo apt download manpages-zh
sudo apt download mariadb-common
sudo apt download mawk
sudo apt download mesa-common-dev
sudo apt download mesa-va-drivers
sudo apt download mesa-vdpau-drivers
sudo apt download mime-support
sudo apt download mlterm
sudo apt download mlterm-common
sudo apt download mlterm-tools
sudo apt download mobile-broadband-provider-info
sudo apt download modemmanager
sudo apt download mono-4.0-gac
sudo apt download mono-csharp-shell
sudo apt download mono-devel
sudo apt download mono-gac
sudo apt download mono-mcs
sudo apt download mono-runtime
sudo apt download mono-runtime-common
sudo apt download mono-runtime-sgen
sudo apt download mono-xbuild
sudo apt download mono-xsp4
sudo apt download mono-xsp4-base
sudo apt download monodoc-base
sudo apt download monodoc-gtk2.0-manual
sudo apt download monodoc-gtk3.0-manual
sudo apt download monodoc-http
sudo apt download monodoc-manual
sudo apt download mount
sudo apt download mousepad
sudo apt download mplayer
sudo apt download mueller7-dict
sudo apt download mupdf
sudo apt download mysql-common
sudo apt download ncurses-base
sudo apt download ncurses-bin
sudo apt download ncurses-term
sudo apt download net-tools
sudo apt download netbase
sudo apt download netcat-traditional
sudo apt download netpbm
sudo apt download network-manager
sudo apt download network-manager-gnome
sudo apt download nftables
sudo apt download nitrogen
sudo apt download nkf
sudo apt download nm-tray
sudo apt download nm-tray-l10n
sudo apt download nodejs
sudo apt download nodejs-doc
sudo apt download notification-daemon
sudo apt download ntfs-3g
sudo apt download ntp
sudo apt download obconf
sudo apt download obsession
sudo apt download openbox
sudo apt download opencc
sudo apt download openjade
sudo apt download openjdk-11-jre
sudo apt download openjdk-11-jre-headless
sudo apt download openssh-client
sudo apt download openssh-server
sudo apt download openssh-sftp-server
sudo apt download openssl
sudo apt download os-prober
sudo apt download p11-kit
sudo apt download p11-kit-modules
sudo apt download p7zip
sudo apt download p7zip-full
sudo apt download pandoc
sudo apt download pandoc-data
sudo apt download pango1.0-tools
sudo apt download parted
sudo apt download passwd
sudo apt download patch
sudo apt download pavucontrol
sudo apt download pciutils
sudo apt download pcmanfm
sudo apt download perl
sudo apt download perl-base
sudo apt download perl-modules-5.28
sudo apt download perl-openssl-defaults
sudo apt download pfb2t1c2pfb
sudo apt download pinentry-curses
sudo apt download pinentry-gnome3
sudo apt download pkg-config
sudo apt download po-debconf
sudo apt download policycoreutils
sudo apt download policykit-1
sudo apt download poppler-data
sudo apt download poppler-utils
sudo apt download powermgmt-base
sudo apt download powertop
sudo apt download ppp
sudo apt download prerex
sudo apt download preview-latex-style
sudo apt download procps
sudo apt download ps2eps
sudo apt download psf-unifont
sudo apt download psmisc
sudo apt download pstoedit
sudo apt download psutils
sudo apt download publicsuffix
sudo apt download pulseaudio
sudo apt download pulseaudio-utils
sudo apt download purifyeps
sudo apt download python
sudo apt download python-all
sudo apt download python-all-dev
sudo apt download python-apt-common
sudo apt download python-asn1crypto
sudo apt download python-cairo
sudo apt download python-cffi-backend
sudo apt download python-configparser
sudo apt download python-crypto
sudo apt download python-cryptography
sudo apt download python-dbus
sudo apt download python-dev
sudo apt download python-entrypoints
sudo apt download python-enum34
sudo apt download python-gi
sudo apt download python-gobject-2
sudo apt download python-gtk2
sudo apt download python-ipaddress
sudo apt download python-keyring
sudo apt download python-keyrings.alt
sudo apt download python-minimal
sudo apt download python-numpy
sudo apt download python-pip
sudo apt download python-pip-whl
sudo apt download python-pkg-resources
sudo apt download python-secretstorage
sudo apt download python-setuptools
sudo apt download python-six
sudo apt download python-talloc
sudo apt download python-tk
sudo apt download python-urwid
sudo apt download python-wheel
sudo apt download python-wicd
sudo apt download python-wxgtk3.0
sudo apt download python-wxgtk3.0-dev
sudo apt download python-wxversion
sudo apt download python-xdg
sudo apt download python2
sudo apt download python2-dev
sudo apt download python2-minimal
sudo apt download python2.7
sudo apt download python2.7-dev
sudo apt download python2.7-minimal
sudo apt download python3
sudo apt download python3-apt
sudo apt download python3-asn1crypto
sudo apt download python3-certifi
sudo apt download python3-cffi-backend
sudo apt download python3-chardet
sudo apt download python3-crypto
sudo apt download python3-cryptography
sudo apt download python3-cson
sudo apt download python3-dbus
sudo apt download python3-debconf
sudo apt download python3-debian
sudo apt download python3-debianbts
sudo apt download python3-dev
sudo apt download python3-distutils
sudo apt download python3-docopt
sudo apt download python3-entrypoints
sudo apt download python3-gi
sudo apt download python3-httplib2
sudo apt download python3-idna
sudo apt download python3-keyring
sudo apt download python3-keyrings.alt
sudo apt download python3-keyutils
sudo apt download python3-lib2to3
sudo apt download python3-mako
sudo apt download python3-markdown
sudo apt download python3-markupsafe
sudo apt download python3-minimal
sudo apt download python3-numpy
sudo apt download python3-pip
sudo apt download python3-pkg-resources
sudo apt download python3-pycurl
sudo apt download python3-pygments
sudo apt download python3-pyqt5
sudo apt download python3-pyqt5.qtsvg
sudo apt download python3-pysimplesoap
sudo apt download python3-reportbug
sudo apt download python3-requests
sudo apt download python3-secretstorage
sudo apt download python3-setuptools
sudo apt download python3-sip
sudo apt download python3-six
sudo apt download python3-speg
sudo apt download python3-uno
sudo apt download python3-urllib3
sudo apt download python3-wheel
sudo apt download python3-xdg
sudo apt download python3-yaml
sudo apt download python3.7
sudo apt download python3.7-dev
sudo apt download python3.7-minimal
sudo apt download qalc
sudo apt download qalculate
sudo apt download qalculate-gtk
sudo apt download qt5-gtk-platformtheme
sudo apt download qttranslations5-l10n
sudo apt download rake
sudo apt download ranger
sudo apt download re
sudo apt download readline-common
sudo apt download reportbug
sudo apt download resolvconf
sudo apt download rfkill
sudo apt download rsyslog
sudo apt download rtkit
sudo apt download ruby
sudo apt download ruby-did-you-mean
sudo apt download ruby-minitest
sudo apt download ruby-net-telnet
sudo apt download ruby-power-assert
sudo apt download ruby-test-unit
sudo apt download ruby-xmlrpc
sudo apt download ruby2.5
sudo apt download rubygems-integration
sudo apt download samba-libs
sudo apt download scrot
sudo apt download sed
sudo apt download selinux-utils
sudo apt download sensible-utils
sudo apt download sgml-base
sudo apt download shared-mime-info
sudo apt download shellinabox
sudo apt download simplescreenrecorder
sudo apt download sntp
sudo apt download sound-theme-freedesktop
sudo apt download ssl-cert
sudo apt download suckless-tools
sudo apt download sudo
sudo apt download swath
sudo apt download swath-data
sudo apt download systemd
sudo apt download systemd-sysv
sudo apt download sysvinit-utils
sudo apt download t1utils
sudo apt download tar
sudo apt download task-amharic
sudo apt download task-arabic
sudo apt download task-asturian
sudo apt download task-basque
sudo apt download task-belarusian
sudo apt download task-bengali
sudo apt download task-bosnian
sudo apt download task-brazilian-portuguese
sudo apt download task-bulgarian
sudo apt download task-catalan
sudo apt download task-chinese-s
sudo apt download task-chinese-t
sudo apt download task-croatian
sudo apt download task-cyrillic
sudo apt download task-czech
sudo apt download task-danish
sudo apt download task-dutch
sudo apt download task-english
sudo apt download task-esperanto
sudo apt download task-estonian
sudo apt download task-finnish
sudo apt download task-french
sudo apt download task-galician
sudo apt download task-german
sudo apt download task-greek
sudo apt download task-gujarati
sudo apt download task-hebrew
sudo apt download task-hindi
sudo apt download task-hungarian
sudo apt download task-icelandic
sudo apt download task-irish
sudo apt download task-italian
sudo apt download task-japanese
sudo apt download task-kazakh
sudo apt download task-khmer
sudo apt download task-korean
sudo apt download task-kurdish
sudo apt download task-laptop
sudo apt download task-latvian
sudo apt download task-lithuanian
sudo apt download task-macedonian
sudo apt download task-malayalam
sudo apt download task-marathi
sudo apt download task-northern-sami
sudo apt download task-norwegian
sudo apt download task-persian
sudo apt download task-polish
sudo apt download task-portuguese
sudo apt download task-punjabi
sudo apt download task-romanian
sudo apt download task-russian
sudo apt download task-serbian
sudo apt download task-slovak
sudo apt download task-slovenian
sudo apt download task-spanish
sudo apt download task-swedish
sudo apt download task-tagalog
sudo apt download task-tamil
sudo apt download task-telugu
sudo apt download task-thai
sudo apt download task-turkish
sudo apt download task-ukrainian
sudo apt download task-welsh
sudo apt download tasksel
sudo apt download tasksel-data
sudo apt download tcl
sudo apt download tcl8.6
sudo apt download teckit
sudo apt download telnet
sudo apt download tex-common
sudo apt download tex-gyre
sudo apt download texinfo
sudo apt download texlive-base
sudo apt download texlive-bibtex-extra
sudo apt download texlive-binaries
sudo apt download texlive-extra-utils
sudo apt download texlive-font-utils
sudo apt download texlive-fonts-extra
sudo apt download texlive-fonts-extra-doc
sudo apt download texlive-fonts-extra-links
sudo apt download texlive-fonts-recommended
sudo apt download texlive-fonts-recommended-doc
sudo apt download texlive-formats-extra
sudo apt download texlive-full
sudo apt download texlive-games
sudo apt download texlive-generic-recommended
sudo apt download texlive-humanities
sudo apt download texlive-humanities-doc
sudo apt download texlive-lang-arabic
sudo apt download texlive-lang-chinese
sudo apt download texlive-lang-cjk
sudo apt download texlive-lang-cyrillic
sudo apt download texlive-lang-czechslovak
sudo apt download texlive-lang-english
sudo apt download texlive-lang-european
sudo apt download texlive-lang-french
sudo apt download texlive-lang-german
sudo apt download texlive-lang-greek
sudo apt download texlive-lang-italian
sudo apt download texlive-lang-japanese
sudo apt download texlive-lang-korean
sudo apt download texlive-lang-other
sudo apt download texlive-lang-polish
sudo apt download texlive-lang-portuguese
sudo apt download texlive-lang-spanish
sudo apt download texlive-latex-base
sudo apt download texlive-latex-base-doc
sudo apt download texlive-latex-extra
sudo apt download texlive-latex-extra-doc
sudo apt download texlive-latex-recommended
sudo apt download texlive-latex-recommended-doc
sudo apt download texlive-luatex
sudo apt download texlive-metapost
sudo apt download texlive-metapost-doc
sudo apt download texlive-music
sudo apt download texlive-pictures
sudo apt download texlive-pictures-doc
sudo apt download texlive-plain-generic
sudo apt download texlive-pstricks
sudo apt download texlive-pstricks-doc
sudo apt download texlive-publishers
sudo apt download texlive-publishers-doc
sudo apt download texlive-science
sudo apt download texlive-science-doc
sudo apt download texlive-xetex
sudo apt download texstudio
sudo apt download texstudio-doc
sudo apt download texstudio-l10n
sudo apt download thunar
sudo apt download thunar-archive-plugin
sudo apt download thunar-data
sudo apt download thunar-media-tags-plugin
sudo apt download thunar-volman
sudo apt download tightvncserver
sudo apt download time
sudo apt download tint2
sudo apt download tipa
sudo apt download tix
sudo apt download tk
sudo apt download tk8.6
sudo apt download tk8.6-blt2.5
sudo apt download tlp
sudo apt download tmispell-voikko
sudo apt download tmux
sudo apt download traceroute
sudo apt download tree
sudo apt download ttf-ubuntu-font-family
sudo apt download ttf-unifont
sudo apt download tumbler
sudo apt download tumbler-common
sudo apt download tzdata
sudo apt download ucf
sudo apt download udev
sudo apt download udhcpc
sudo apt download udiskie
sudo apt download udisks2
sudo apt download uim
sudo apt download uim-data
sudo apt download uim-fep
sudo apt download uim-gtk2.0
sudo apt download uim-gtk2.0-immodule
sudo apt download uim-gtk3
sudo apt download uim-gtk3-immodule
sudo apt download uim-plugins
sudo apt download uim-qt5
sudo apt download uim-qt5-immodule
sudo apt download uim-xim
sudo apt download unicon-imc2
sudo apt download unifont
sudo apt download uno-libs3
sudo apt download unzip
sudo apt download upower
sudo apt download ure
sudo apt download usb-modeswitch
sudo apt download usb-modeswitch-data
sudo apt download usb.ids
sudo apt download usbmuxd
sudo apt download usbutils
sudo apt download util-linux
sudo apt download util-linux-locales
sudo apt download uuid-dev
sudo apt download uuid-runtime
sudo apt download va-driver-all
sudo apt download vdpau-driver-all
sudo apt download vifm
sudo apt download vim
sudo apt download vim-addon-manager
sudo apt download vim-common
sudo apt download vim-runtime
sudo apt download vim-tiny
sudo apt download vlc
sudo apt download vlc-bin
sudo apt download vlc-data
sudo apt download vlc-l10n
sudo apt download vlc-plugin-base
sudo apt download vlc-plugin-notify
sudo apt download vlc-plugin-qt
sudo apt download vlc-plugin-samba
sudo apt download vlc-plugin-skins2
sudo apt download vlc-plugin-video-output
sudo apt download vlc-plugin-video-splitter
sudo apt download vlc-plugin-visualization
sudo apt download voikko-fi
sudo apt download vorbis-tools
sudo apt download vprerex
sudo apt download w3m
sudo apt download w3m-img
sudo apt download wamerican
sudo apt download wayland-protocols
sudo apt download wbrazilian
sudo apt download wbulgarian
sudo apt download wcatalan
sudo apt download wdanish
sudo apt download wdutch
sudo apt download wfrench
sudo apt download wget
sudo apt download whiptail
sudo apt download wicd
sudo apt download wicd-curses
sudo apt download wicd-daemon
sudo apt download wireless-regdb
sudo apt download wireless-tools
sudo apt download witalian
sudo apt download wngerman
sudo apt download wnorwegian
sudo apt download wpasupplicant
sudo apt download wpolish
sudo apt download wportuguese
sudo apt download wspanish
sudo apt download wswedish
sudo apt download wx-common
sudo apt download wx3.0-headers
sudo apt download x11-apps
sudo apt download x11-common
sudo apt download x11-session-utils
sudo apt download x11-utils
sudo apt download x11-xkb-utils
sudo apt download x11-xserver-utils
sudo apt download x11proto-composite-dev
sudo apt download x11proto-core-dev
sudo apt download x11proto-damage-dev
sudo apt download x11proto-dev
sudo apt download x11proto-fixes-dev
sudo apt download x11proto-input-dev
sudo apt download x11proto-randr-dev
sudo apt download x11proto-record-dev
sudo apt download x11proto-xext-dev
sudo apt download x11proto-xf86vidmode-dev
sudo apt download x11proto-xinerama-dev
sudo apt download xarchiver
sudo apt download xauth
sudo apt download xaw3dg
sudo apt download xbitmaps
sudo apt download xclip
sudo apt download xdg-dbus-proxy
sudo apt download xdg-user-dirs
sudo apt download xdg-utils
sudo apt download xfburn
sudo apt download xfconf
sudo apt download xfishtank
sudo apt download xfonts-100dpi
sudo apt download xfonts-75dpi
sudo apt download xfonts-base
sudo apt download xfonts-encodings
sudo apt download xfonts-scalable
sudo apt download xfonts-unifont
sudo apt download xfonts-utils
sudo apt download xinit
sudo apt download xkb-data
sudo apt download xml-core
sudo apt download xorg
sudo apt download xorg-docs-core
sudo apt download xorg-sgml-doctools
sudo apt download xorgxrdp
sudo apt download xrdp
sudo apt download xserver-common
sudo apt download xserver-xorg
sudo apt download xserver-xorg-core
sudo apt download xserver-xorg-input-all
sudo apt download xserver-xorg-input-libinput
sudo apt download xserver-xorg-input-wacom
sudo apt download xserver-xorg-legacy
sudo apt download xserver-xorg-video-all
sudo apt download xserver-xorg-video-amdgpu
sudo apt download xserver-xorg-video-ati
sudo apt download xserver-xorg-video-fbdev
sudo apt download xserver-xorg-video-intel
sudo apt download xserver-xorg-video-nouveau
sudo apt download xserver-xorg-video-qxl
sudo apt download xserver-xorg-video-radeon
sudo apt download xserver-xorg-video-vesa
sudo apt download xserver-xorg-video-vmware
sudo apt download xterm
sudo apt download xtrans-dev
sudo apt download xvkbd
sudo apt download xxd
sudo apt download xz-utils
sudo apt download yudit-common
sudo apt download zathura
sudo apt download zathura-pdf-poppler
sudo apt download zhcon
sudo apt download zhcon-data
sudo apt download zip
sudo apt download zlib1g
sudo apt download zlib1g-dev
