#!/bin/bash

## #####################################################################################################################
## Individual debs and dependencies for: vim timux vifm tlp aspell tlp git hostapd dnsmasq
## #####################################################################################################################

sudo apt download acpid
sudo apt download adduser
sudo apt download adwaita-icon-theme
sudo apt download anacron
sudo apt download apt
sudo apt download apt-listchanges
sudo apt download apt-utils
sudo apt download aspell
sudo apt download aspell-am
sudo apt download aspell-ar
sudo apt download aspell-ar-large
sudo apt download aspell-bg
sudo apt download aspell-bn
sudo apt download aspell-ca
sudo apt download aspell-cs
sudo apt download aspell-cy
sudo apt download aspell-da
sudo apt download aspell-de
sudo apt download aspell-el
sudo apt download aspell-eo
sudo apt download aspell-es
sudo apt download aspell-et
sudo apt download aspell-eu
sudo apt download aspell-eu-es
sudo apt download aspell-fa
sudo apt download aspell-fr
sudo apt download aspell-ga
sudo apt download aspell-gl-minimos
sudo apt download aspell-gu
sudo apt download aspell-he
sudo apt download aspell-hi
sudo apt download aspell-hr
sudo apt download aspell-hu
sudo apt download aspell-is
sudo apt download aspell-it
sudo apt download aspell-kk
sudo apt download aspell-ku
sudo apt download aspell-lt
sudo apt download aspell-lv
sudo apt download aspell-ml
sudo apt download aspell-mr
sudo apt download aspell-nl
sudo apt download aspell-no
sudo apt download aspell-pa
sudo apt download aspell-pl
sudo apt download aspell-pt-br
sudo apt download aspell-pt-pt
sudo apt download aspell-ro
sudo apt download aspell-ru
sudo apt download aspell-sk
sudo apt download aspell-sl
sudo apt download aspell-sv
sudo apt download aspell-ta
sudo apt download aspell-te
sudo apt download aspell-tl
sudo apt download aspell-uk
sudo apt download at-spi2-core
sudo apt download avahi-autoipd
sudo apt download base-files
sudo apt download base-passwd
sudo apt download bash
sudo apt download bash-completion
sudo apt download bidiv
sudo apt download bind9-host
sudo apt download binutils
sudo apt download binutils-common
sudo apt download binutils-x86-64-linux-gnu
sudo apt download blt
sudo apt download bluetooth
sudo apt download bluez
sudo apt download bsdmainutils
sudo apt download bsdutils
sudo apt download build-essential
sudo apt download busybox
sudo apt download bzip2
sudo apt download ca-certificates
sudo apt download console-setup
sudo apt download console-setup-linux
sudo apt download coreutils
sudo apt download cpio
sudo apt download cpp
sudo apt download cpp-8
sudo apt download crda
sudo apt download cron
sudo apt download culmus
sudo apt download dash
sudo apt download dbus
sudo apt download dbus-user-session
sudo apt download dconf-cli
sudo apt download dconf-gsettings-backend
sudo apt download dconf-service
sudo apt download debconf
sudo apt download debconf-i18n
sudo apt download debian-archive-keyring
sudo apt download debian-faq
sudo apt download debian-reference-common
sudo apt download debian-reference-es
sudo apt download debian-reference-it
sudo apt download debianutils
sudo apt download dictionaries-common
sudo apt download diffutils
sudo apt download dirmngr
sudo apt download distro-info-data
sudo apt download dkms
sudo apt download dmidecode
sudo apt download dmsetup
sudo apt download dns-root-data
sudo apt download dnsmasq
sudo apt download dnsmasq-base
sudo apt download doc-debian
sudo apt download dpkg
sudo apt download dpkg-dev
sudo apt download e2fsprogs
sudo apt download efibootmgr
sudo apt download elinks
sudo apt download elinks-data
sudo apt download emacsen-common
sudo apt download enchant
sudo apt download ethtool
sudo apt download fakeroot
sudo apt download fbterm
sudo apt download fdisk
sudo apt download file
sudo apt download findutils
sudo apt download firmware-amd-graphics
sudo apt download firmware-iwlwifi
sudo apt download firmware-linux-free
sudo apt download firmware-linux-nonfree
sudo apt download firmware-misc-nonfree
sudo apt download fontconfig
sudo apt download fontconfig-config
sudo apt download fonts-arabeyes
sudo apt download fonts-dejavu-core
sudo apt download fonts-lato
sudo apt download fortune-mod
sudo apt download fortunes-debian-hints
sudo apt download fortunes-it
sudo apt download g++
sudo apt download g++-8
sudo apt download gcc
sudo apt download gcc-8
sudo apt download gcc-8-base
sudo apt download gdbm-l10n
sudo apt download geoip-database
sudo apt download gettext-base
sudo apt download gir1.2-atk-1.0
sudo apt download gir1.2-freedesktop
sudo apt download gir1.2-gdkpixbuf-2.0
sudo apt download gir1.2-glib-2.0
sudo apt download gir1.2-gtk-3.0
sudo apt download gir1.2-ibus-1.0
sudo apt download gir1.2-pango-1.0
sudo apt download git
sudo apt download git-man
sudo apt download glib-networking
sudo apt download glib-networking-common
sudo apt download glib-networking-services
sudo apt download gnupg
sudo apt download gnupg-l10n
sudo apt download gnupg-utils
sudo apt download gpg
sudo apt download gpg-agent
sudo apt download gpg-wks-client
sudo apt download gpg-wks-server
sudo apt download gpgconf
sudo apt download gpgsm
sudo apt download gpgv
sudo apt download grep
sudo apt download groff-base
sudo apt download grub-common
sudo apt download grub-efi-amd64
sudo apt download grub-efi-amd64-bin
sudo apt download grub-efi-amd64-signed
sudo apt download grub2-common
sudo apt download gsettings-desktop-schemas
sudo apt download gtk-update-icon-cache
sudo apt download gzip
sudo apt download haveged
sudo apt download hdparm
sudo apt download hicolor-icon-theme
sudo apt download hostapd
sudo apt download hostname
sudo apt download hspell
sudo apt download hunspell
sudo apt download hunspell-en-us
sudo apt download hunspell-hu
sudo apt download hunspell-se
sudo apt download iamerican
sudo apt download ibrazilian
sudo apt download ibritish
sudo apt download ibulgarian
sudo apt download ibus
sudo apt download ibus-clutter
sudo apt download ibus-gtk
sudo apt download ibus-gtk3
sudo apt download ibus-m17n
sudo apt download icatalan
sudo apt download idanish
sudo apt download idutch
sudo apt download ienglish-common
sudo apt download ifplugd
sudo apt download ifrench-gut
sudo apt download ifupdown
sudo apt download ihungarian
sudo apt download iitalian
sudo apt download ilithuanian
sudo apt download im-config
sudo apt download ingerman
sudo apt download init
sudo apt download init-system-helpers
sudo apt download initramfs-tools
sudo apt download initramfs-tools-core
sudo apt download inorwegian
sudo apt download intel-microcode
sudo apt download ipolish
sudo apt download iportuguese
sudo apt download iproute2
sudo apt download iptables
sudo apt download iputils-ping
sudo apt download irussian
sudo apt download isc-dhcp-client
sudo apt download isc-dhcp-common
sudo apt download iso-codes
sudo apt download ispanish
sudo apt download ispell
sudo apt download iswiss
sudo apt download itools
sudo apt download iucode-tool
sudo apt download iukrainian
sudo apt download iw
sudo apt download javascript-common
sudo apt download kbd
sudo apt download keyboard-configuration
sudo apt download khmerconverter
sudo apt download klibc-utils
sudo apt download kmod
sudo apt download konwert
sudo apt download konwert-filters
sudo apt download krb5-locales
sudo apt download less
sudo apt download libacl1
sudo apt download libalgorithm-diff-perl
sudo apt download libalgorithm-diff-xs-perl
sudo apt download libalgorithm-merge-perl
sudo apt download libapparmor1
sudo apt download libapt-inst2.0
sudo apt download libapt-pkg5.0
sudo apt download libarchive13
sudo apt download libargon2-1
sudo apt download libasan5
sudo apt download libasound2
sudo apt download libasound2-data
sudo apt download libaspell15
sudo apt download libassuan0
sudo apt download libatk-bridge2.0-0
sudo apt download libatk1.0-0
sudo apt download libatk1.0-data
sudo apt download libatomic1
sudo apt download libatspi2.0-0
sudo apt download libattr1
sudo apt download libaudit-common
sudo apt download libaudit1
sudo apt download libavahi-client3
sudo apt download libavahi-common-data
sudo apt download libavahi-common3
sudo apt download libbind9-161
sudo apt download libbinutils
sudo apt download libblkid1
sudo apt download libbluetooth3
sudo apt download libbsd0
sudo apt download libbz2-1.0
sudo apt download libc-bin
sudo apt download libc-dev-bin
sudo apt download libc-l10n
sudo apt download libc6
sudo apt download libc6-dev
sudo apt download libcairo-gobject2
sudo apt download libcairo2
sudo apt download libcap-ng0
sudo apt download libcap2
sudo apt download libcap2-bin
sudo apt download libcc1-0
sudo apt download libclutter-1.0-0
sudo apt download libclutter-1.0-common
sudo apt download libclutter-imcontext-0.1-0
sudo apt download libclutter-imcontext-0.1-bin
sudo apt download libcogl-common
sudo apt download libcogl-pango20
sudo apt download libcogl-path20
sudo apt download libcogl20
sudo apt download libcolord2
sudo apt download libcom-err2
sudo apt download libcpupower1
sudo apt download libcroco3
sudo apt download libcryptsetup12
sudo apt download libcups2
sudo apt download libcurl3-gnutls
sudo apt download libdaemon0
sudo apt download libdatrie1
sudo apt download libdb5.3
sudo apt download libdbus-1-3
sudo apt download libdconf1
sudo apt download libdebconfclient0
sudo apt download libdevmapper1.02.1
sudo apt download libdns-export1104
sudo apt download libdns1104
sudo apt download libdouble-conversion1
sudo apt download libdpkg-perl
sudo apt download libdrm-amdgpu1
sudo apt download libdrm-common
sudo apt download libdrm-intel1
sudo apt download libdrm-nouveau2
sudo apt download libdrm-radeon1
sudo apt download libdrm2
sudo apt download libdw1
sudo apt download libedit2
sudo apt download libefiboot1
sudo apt download libefivar1
sudo apt download libegl-mesa0
sudo apt download libegl1
sudo apt download libegl1-mesa
sudo apt download libelf1
sudo apt download libenchant-voikko
sudo apt download libenchant1c2a
sudo apt download libepoxy0
sudo apt download liberror-perl
sudo apt download libestr0
sudo apt download libev4
sudo apt download libevdev2
sudo apt download libevent-2.1-6
sudo apt download libexpat1
sudo apt download libext2fs2
sudo apt download libfakeroot
sudo apt download libfastjson4
sudo apt download libfdisk1
sudo apt download libffi6
sudo apt download libfile-fcntllock-perl
sudo apt download libfontconfig1
sudo apt download libfontenc1
sudo apt download libfreetype6
sudo apt download libfribidi0
sudo apt download libfsplib0
sudo apt download libfstrm0
sudo apt download libfuse2
sudo apt download libgbm1
sudo apt download libgc1c2
sudo apt download libgcc-8-dev
sudo apt download libgcc1
sudo apt download libgcrypt20
sudo apt download libgd3
sudo apt download libgdbm-compat4
sudo apt download libgdbm6
sudo apt download libgdk-pixbuf2.0-0
sudo apt download libgdk-pixbuf2.0-bin
sudo apt download libgdk-pixbuf2.0-common
sudo apt download libgeoip1
sudo apt download libgirepository-1.0-1
sudo apt download libgl1
sudo apt download libgl1-mesa-dri
sudo apt download libglapi-mesa
sudo apt download libglib2.0-0
sudo apt download libglib2.0-data
sudo apt download libglibmm-2.4-1v5
sudo apt download libglvnd0
sudo apt download libglx-mesa0
sudo apt download libglx0
sudo apt download libgmp10
sudo apt download libgnutls30
sudo apt download libgomp1
sudo apt download libgpg-error0
sudo apt download libgpm2
sudo apt download libgraphite2-3
sudo apt download libgssapi-krb5-2
sudo apt download libgtk-3-0
sudo apt download libgtk-3-bin
sudo apt download libgtk-3-common
sudo apt download libgudev-1.0-0
sudo apt download libharfbuzz0b
sudo apt download libhavege1
sudo apt download libhdate1
sudo apt download libhfstospell10
sudo apt download libhogweed4
sudo apt download libhunspell-1.7-0
sudo apt download libibus-1.0-5
sudo apt download libice6
sudo apt download libicu63
sudo apt download libidn11
sudo apt download libidn2-0
sudo apt download libinput-bin
sudo apt download libinput10
sudo apt download libip4tc0
sudo apt download libip6tc0
sudo apt download libiptc0
sudo apt download libisc-export1100
sudo apt download libisc1100
sudo apt download libisccc161
sudo apt download libisccfg163
sudo apt download libisl19
sudo apt download libitl0
sudo apt download libitm1
sudo apt download libiw30
sudo apt download libjansson4
sudo apt download libjbig0
sudo apt download libjim0.77
sudo apt download libjpeg62-turbo
sudo apt download libjs-jquery
sudo apt download libjson-c3
sudo apt download libjson-glib-1.0-0
sudo apt download libjson-glib-1.0-common
sudo apt download libk5crypto3
sudo apt download libkeyutils1
sudo apt download libklibc
sudo apt download libkmod2
sudo apt download libkrb5-3
sudo apt download libkrb5support0
sudo apt download libksba8
sudo apt download liblcms2-2
sudo apt download libldap-2.4-2
sudo apt download libldap-common
sudo apt download libllvm7
sudo apt download liblmdb0
sudo apt download liblocale-gettext-perl
sudo apt download liblockfile-bin
sudo apt download liblognorm5
sudo apt download liblsan0
sudo apt download liblua5.1-0
sudo apt download liblwres161
sudo apt download liblz4-1
sudo apt download liblzma5
sudo apt download libm17n-0
sudo apt download libmagic-mgc
sudo apt download libmagic1
sudo apt download libmbim-glib4
sudo apt download libmbim-proxy
sudo apt download libmm-glib0
sudo apt download libmnl0
sudo apt download libmount1
sudo apt download libmpc3
sudo apt download libmpdec2
sudo apt download libmpfr6
sudo apt download libmpx2
sudo apt download libmtdev1
sudo apt download libncurses6
sudo apt download libncursesw6
sudo apt download libndp0
sudo apt download libnetfilter-conntrack3
sudo apt download libnettle6
sudo apt download libnewt0.52
sudo apt download libnfnetlink0
sudo apt download libnftnl11
sudo apt download libnghttp2-14
sudo apt download libnl-3-200
sudo apt download libnl-genl-3-200
sudo apt download libnl-route-3-200
sudo apt download libnm0
sudo apt download libnotify4
sudo apt download libnpth0
sudo apt download libnss-myhostname
sudo apt download libnss-systemd
sudo apt download libopencc2
sudo apt download libopencc2-data
sudo apt download libotf0
sudo apt download libp11-kit0
sudo apt download libpam-modules
sudo apt download libpam-modules-bin
sudo apt download libpam-runtime
sudo apt download libpam-systemd
sudo apt download libpam0g
sudo apt download libpango-1.0-0
sudo apt download libpangocairo-1.0-0
sudo apt download libpangoft2-1.0-0
sudo apt download libpangoxft-1.0-0
sudo apt download libpcap0.8
sudo apt download libpci3
sudo apt download libpciaccess0
sudo apt download libpcre2-16-0
sudo apt download libpcre2-8-0
sudo apt download libpcre3
sudo apt download libpcsclite1
sudo apt download libperl5.28
sudo apt download libpipeline1
sudo apt download libpixman-1-0
sudo apt download libpng16-16
sudo apt download libpolkit-agent-1-0
sudo apt download libpolkit-backend-1-0
sudo apt download libpolkit-gobject-1-0
sudo apt download libpopt0
sudo apt download libprocps7
sudo apt download libprotobuf-c1
sudo apt download libproxy1v5
sudo apt download libpsl5
sudo apt download libpth20
sudo apt download libpython-stdlib
sudo apt download libpython2-stdlib
sudo apt download libpython2.7-minimal
sudo apt download libpython2.7-stdlib
sudo apt download libpython3-stdlib
sudo apt download libpython3.7-minimal
sudo apt download libpython3.7-stdlib
sudo apt download libqmi-glib5
sudo apt download libqmi-proxy
sudo apt download libqt5core5a
sudo apt download libqt5dbus5
sudo apt download libqt5gui5
sudo apt download libqt5network5
sudo apt download libqt5svg5
sudo apt download libqt5widgets5
sudo apt download libquadmath0
sudo apt download libreadline7
sudo apt download librecode0
sudo apt download librest-0.7-0
sudo apt download librsvg2-2
sudo apt download librsvg2-common
sudo apt download librtmp1
sudo apt download libruby2.5
sudo apt download libsasl2-2
sudo apt download libsasl2-modules
sudo apt download libsasl2-modules-db
sudo apt download libseccomp2
sudo apt download libselinux1
sudo apt download libsemanage-common
sudo apt download libsemanage1
sudo apt download libsensors-config
sudo apt download libsensors5
sudo apt download libsepol1
sudo apt download libsigc++-2.0-0v5
sudo apt download libslang2
sudo apt download libsm6
sudo apt download libsmartcols1
sudo apt download libsoup-gnome2.4-1
sudo apt download libsoup2.4-1
sudo apt download libsqlite3-0
sudo apt download libss2
sudo apt download libssh2-1
sudo apt download libssl1.1
sudo apt download libstdc++-8-dev
sudo apt download libstdc++6
sudo apt download libsystemd0
sudo apt download libtasn1-6
sudo apt download libtcl8.6
sudo apt download libteamdctl0
sudo apt download libtext-charwidth-perl
sudo apt download libtext-iconv-perl
sudo apt download libtext-wrapi18n-perl
sudo apt download libthai-data
sudo apt download libthai0
sudo apt download libtiff5
sudo apt download libtinfo6
sudo apt download libtk8.6
sudo apt download libtre5
sudo apt download libtsan0
sudo apt download libubsan1
sudo apt download libuchardet0
sudo apt download libudev1
sudo apt download libunistring2
sudo apt download libusb-1.0-0
sudo apt download libutempter0
sudo apt download libuuid1
sudo apt download libvoikko1
sudo apt download libwacom-bin
sudo apt download libwacom-common
sudo apt download libwacom2
sudo apt download libwayland-client0
sudo apt download libwayland-cursor0
sudo apt download libwayland-egl1
sudo apt download libwayland-server0
sudo apt download libwebp6
sudo apt download libwrap0
sudo apt download libx11-6
sudo apt download libx11-data
sudo apt download libx11-xcb1
sudo apt download libx86-1
sudo apt download libxau6
sudo apt download libxcb-dri2-0
sudo apt download libxcb-dri3-0
sudo apt download libxcb-glx0
sudo apt download libxcb-icccm4
sudo apt download libxcb-image0
sudo apt download libxcb-keysyms1
sudo apt download libxcb-present0
sudo apt download libxcb-randr0
sudo apt download libxcb-render-util0
sudo apt download libxcb-render0
sudo apt download libxcb-shape0
sudo apt download libxcb-shm0
sudo apt download libxcb-sync1
sudo apt download libxcb-util0
sudo apt download libxcb-xfixes0
sudo apt download libxcb-xinerama0
sudo apt download libxcb-xkb1
sudo apt download libxcb1
sudo apt download libxcomposite1
sudo apt download libxcursor1
sudo apt download libxdamage1
sudo apt download libxdmcp6
sudo apt download libxext6
sudo apt download libxfixes3
sudo apt download libxft2
sudo apt download libxi6
sudo apt download libxinerama1
sudo apt download libxkbcommon-x11-0
sudo apt download libxkbcommon0
sudo apt download libxml2
sudo apt download libxmuu1
sudo apt download libxpm4
sudo apt download libxrandr2
sudo apt download libxrender1
sudo apt download libxshmfence1
sudo apt download libxss1
sudo apt download libxt6
sudo apt download libxtables12
sudo apt download libxtst6
sudo apt download libxxf86vm1
sudo apt download libyaml-0-2
sudo apt download libzstd1
sudo apt download linux-base
sudo apt download linux-compiler-gcc-8-x86
sudo apt download linux-cpupower
sudo apt download linux-headers-4.19.0-10-amd64
sudo apt download linux-headers-4.19.0-10-common
sudo apt download linux-headers-amd64
sudo apt download linux-image-4.19.0-10-amd64
sudo apt download linux-image-amd64
sudo apt download linux-kbuild-4.19
sudo apt download linux-libc-dev
sudo apt download live-task-localisation
sudo apt download live-task-recommended
sudo apt download locales
sudo apt download login
sudo apt download logrotate
sudo apt download lsb-base
sudo apt download lsb-release
sudo apt download lsof
sudo apt download lv
sudo apt download m17n-db
sudo apt download maint-guide-it
sudo apt download make
sudo apt download man-db
sudo apt download manpages
sudo apt download manpages-de
sudo apt download manpages-dev
sudo apt download manpages-es
sudo apt download manpages-hu
sudo apt download manpages-it
sudo apt download manpages-ja
sudo apt download manpages-ja-dev
sudo apt download manpages-pl
sudo apt download manpages-pl-dev
sudo apt download manpages-pt
sudo apt download manpages-tr
sudo apt download manpages-zh
sudo apt download mawk
sudo apt download mime-support
sudo apt download mlterm
sudo apt download mlterm-common
sudo apt download mlterm-tools
sudo apt download modemmanager
sudo apt download mokutil
sudo apt download mount
sudo apt download mueller7-dict
sudo apt download ncurses-base
sudo apt download ncurses-bin
sudo apt download ncurses-term
sudo apt download netbase
sudo apt download netcat-traditional
sudo apt download network-manager
sudo apt download nkf
sudo apt download notification-daemon
sudo apt download opencc
sudo apt download openssh-client
sudo apt download openssh-server
sudo apt download openssh-sftp-server
sudo apt download openssl
sudo apt download os-prober
sudo apt download passwd
sudo apt download patch
sudo apt download pciutils
sudo apt download perl
sudo apt download perl-base
sudo apt download perl-modules-5.28
sudo apt download pinentry-curses
sudo apt download policykit-1
sudo apt download powermgmt-base
sudo apt download powertop
sudo apt download ppp
sudo apt download procps
sudo apt download psf-unifont
sudo apt download publicsuffix
sudo apt download python
sudo apt download python-apt-common
sudo apt download python-minimal
sudo apt download python-tk
sudo apt download python2
sudo apt download python2-minimal
sudo apt download python2.7
sudo apt download python2.7-minimal
sudo apt download python3
sudo apt download python3-apt
sudo apt download python3-certifi
sudo apt download python3-chardet
sudo apt download python3-debconf
sudo apt download python3-debian
sudo apt download python3-debianbts
sudo apt download python3-gi
sudo apt download python3-httplib2
sudo apt download python3-idna
sudo apt download python3-minimal
sudo apt download python3-pkg-resources
sudo apt download python3-pycurl
sudo apt download python3-pysimplesoap
sudo apt download python3-reportbug
sudo apt download python3-requests
sudo apt download python3-six
sudo apt download python3-urllib3
sudo apt download python3.7
sudo apt download python3.7-minimal
sudo apt download qt5-gtk-platformtheme
sudo apt download qttranslations5-l10n
sudo apt download rake
sudo apt download re
sudo apt download readline-common
sudo apt download reportbug
sudo apt download resolvconf
sudo apt download rfkill
sudo apt download rsyslog
sudo apt download ruby
sudo apt download ruby-did-you-mean
sudo apt download ruby-minitest
sudo apt download ruby-net-telnet
sudo apt download ruby-power-assert
sudo apt download ruby-test-unit
sudo apt download ruby-xmlrpc
sudo apt download ruby2.5
sudo apt download rubygems-integration
sudo apt download sed
sudo apt download sensible-utils
sudo apt download shared-mime-info
sudo apt download shim-helpers-amd64-signed
sudo apt download shim-signed
sudo apt download shim-signed-common
sudo apt download shim-unsigned
sudo apt download sudo
sudo apt download swath
sudo apt download swath-data
sudo apt download systemd
sudo apt download systemd-sysv
sudo apt download sysvinit-utils
sudo apt download tar
sudo apt download task-english
sudo apt download tasksel
sudo apt download tasksel-data
sudo apt download tcl
sudo apt download tcl8.6
sudo apt download telnet
sudo apt download time
sudo apt download tix
sudo apt download tk8.6-blt2.5
sudo apt download tlp
sudo apt download tlp-rdw
sudo apt download tmispell-voikko
sudo apt download tmux
sudo apt download traceroute
sudo apt download ttf-unifont
sudo apt download tzdata
sudo apt download ucf
sudo apt download udev
sudo apt download unicon-imc2
sudo apt download unifont
sudo apt download unzip
sudo apt download usb-modeswitch
sudo apt download usb-modeswitch-data
sudo apt download usb.ids
sudo apt download usbutils
sudo apt download util-linux
sudo apt download util-linux-locales
sudo apt download uuid-runtime
sudo apt download vifm
sudo apt download vim
sudo apt download vim-addon-manager
sudo apt download vim-common
sudo apt download vim-runtime
sudo apt download vim-tiny
sudo apt download voikko-fi
sudo apt download w3m
sudo apt download wamerican
sudo apt download wbrazilian
sudo apt download wbulgarian
sudo apt download wcatalan
sudo apt download wdanish
sudo apt download wdutch
sudo apt download wfrench
sudo apt download wget
sudo apt download whiptail
sudo apt download wireless-regdb
sudo apt download wireless-tools
sudo apt download witalian
sudo apt download wngerman
sudo apt download wnorwegian
sudo apt download wpasupplicant
sudo apt download wpolish
sudo apt download wportuguese
sudo apt download wspanish
sudo apt download wswedish
sudo apt download x11-common
sudo apt download xauth
sudo apt download xdg-user-dirs
sudo apt download xfonts-encodings
sudo apt download xfonts-unifont
sudo apt download xfonts-utils
sudo apt download xkb-data
sudo apt download xxd
sudo apt download xz-utils
sudo apt download zhcon
sudo apt download zhcon-data
sudo apt download zip
sudo apt download zlib1g
