#!/bin/bash

## how to use this script:
## use wickerscript's ./pkgdownload to download dependancy debs for a package
## then use this script to unpack and generate an (non-essential) installer script.
## Installer isnot recommened for big dependancies like Xorg.
## ./unpack-install file.tar.gz
## *.tar.gz must be generated by the pkgdownload script

tmpRoot=$(pwd)
inputGzipFile=$1

## gunzip and tar in one step
## gunzip file.gz
## tar -xf file.tar

filename="$(basename -- $inputGzipFile)"
filename="${filename%.tar*}"

tar xvfz $inputGzipFile

cd $filename

outputFile=$tmpRoot/install_$filename.sh

echo '#!/bin/bash' >> $outputFile
chmod +x $outputFile

while IFS= read -r line
do
	echo "sudo dpkg -i $filename/$line*" >> $outputFile
	echo "sudo apt install -f" >> $outputFile
done < dependencies*

